nvim-neorg/neorg

README.md

Aloha,
I added how to configure vim-plug with init.vim for initial configuration.

Add vim-plug to README

---

.github/workflows/default.yml

Example pipeline on PR [here](https://github.com/vuki656/neorg/pull/1)
Output for failing build [here](https://github.com/vuki656/neorg/runs/3210483050?check_suite_focus=true)

feat(pipeline): stylua check

---

docs/EXAMPLE.norg

Let me know if something is missing, I added everything from the spec that seems to be implemented.
Closes #52

feat(docs): add EXAMPLE.norg

---

lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/norg/completion/module.lua
lua/neorg/modules/core/norg/esupports/module.lua

Something is not yet quite working as expected because the `completion` module appears to be unhappy with the way I am trying to load things.
Hopefully @vhyrro knows what's going on here. Nonetheless, this is hopefully a decent starting point.

Extract `get_ts_utils()` method

---

doc/neorg.norg
doc/tags

Backport #92

---

doc/neorg.norg
docs/EXAMPLE.norg

fix(inter-file-link): inter-file link syntax docs

---

lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/norg/concealer/module.lua

As always, everything is configurable to your hearts content :+1: 
EDIT: new screenshot

Conceal all quote levels individually

---

lua/neorg/modules/core/queries/native/module.lua

As requested, I did a back port of the queries module from #99 (`gtd_base` branch). 
The advantages will be to already have it on unstable in order to advance on certain PR's like #88, and to have some feedback about this module in order to improve it.

Backport of queries module

---

lua/neorg/modules/core/norg/concealer/module.lua

fix(conceal): concealment of basic markup at the beginning of lines

---

lua/neorg/modules/core/norg/dirman/module.lua

Previously added on `gtd_base` branch

Add functions to dirman

---

doc/neorg.norg
doc/roadmap.norg
doc/tags
docs/EXAMPLE.norg
docs/NFF-0.1-spec.md

This PR applies various syntax updates which we have gathered in discussions and on discord:
- #38 
- #95 
- #103

Syntax Updates

---

lua/neorg/external/helpers.lua
lua/neorg/modules.lua
lua/neorg/modules/base.lua
lua/neorg/modules/core/keybinds/default_keybinds.lua
lua/neorg/modules/core/keybinds/module.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/ui/module.lua
lua/neorg/modules/core/ui/selection_popup.lua
lua/neorg/modules/core/ui/text_popup.lua

This is the rework of the multiple modules, which was causing huge problems before

Multifile modules

---

lua/neorg/modules/core/gtd/ui/views_popup_helpers.lua

feat(gtd.ui.generate_date_flags): `today` preset

---

lua/neorg/modules/core/gtd/queries/retrievers.lua
lua/neorg/modules/core/gtd/ui/displayers.lua

This pull request is for [this](https://github.com/nvim-neorg/neorg/discussions/217) discussion

Refactor gtd display

---

doc/gtd.norg
lua/neorg/modules/core/keybinds/module.lua

should I use
`{# Clarify}[Clarify]`
or only `{# Clarify}`?

update gtd links to new format

---

doc/neorg.norg
lua/neorg/modules/core/keybinds/default_keybinds.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/concealer/preset_brave.lua
lua/neorg/modules/core/norg/concealer/preset_safe.lua

Improves the TS-based concealing behavior

Improved Concealing

---

doc/neorg.norg
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/esupports/hop/module.lua
queries/norg/highlights.scm

This updates Neorg in accordance with https://github.com/nvim-neorg/tree-sitter-norg/pull/21

TS link refactoring

---

docs/NFF-0.1-spec.md

Fixed some mistakes in the descriptions of links and anchors

Fix some mistakes in NFF-0.1-spec

---

lua/neorg/modules/core/gtd/queries/helpers.lua
lua/neorg/modules/core/gtd/ui/capture_popup.lua
lua/neorg/modules/core/gtd/ui/edit_popup.lua
tests/core/gtd/queries/helpers_spec.lua
tests/core/gtd/ui/displayers_spec.lua

this allows to have a time.due/start for example for the 4th monday that will come.
The format is 4mon.

feat(gtd): allow count for weekdays

---

lua/neorg/modules/core/norg/esupports/metagen/module.lua

When you run `:Neorg inject-metadata`, it will create another copy of the metadata instead of replacing it. Not sure if this was intended.

refactor(metagen): update metadata if it already exists

---

lua/neorg/modules/core/gtd/ui/edit_popup.lua
lua/neorg/modules/core/norg/journal/module.lua

checks if file exists and opens it if it does
This will close https://github.com/nvim-neorg/neorg/issues/384
Also use correct separator for paths

fix(journal): existing files would get overwritten

---

lua/neorg/modules/core/gtd/helpers/module.lua
tests/core/gtd/helpers/helpers_spec.lua

Some tests for the public helper functions for gtd.
Slight readability refactor on the tasks callback
First PR, new to lua, be nice 😄

Gtd helpers tests

---

lua/neorg/modules/core/integrations/treesitter/module.lua

(fixes https://github.com/nvim-neorg/neorg/issues/442)

fix(treesitter): readd deleted functions 

---

README.md

not merge yet because modules aren't ready

docs(readme): more external modules

---

lua/neorg.lua
lua/neorg/events.lua
lua/neorg/modules.lua
lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/gtd/queries/retrievers.lua
lua/neorg/modules/core/gtd/ui/capture_popup.lua
lua/neorg/modules/core/gtd/ui/edit_popup.lua
lua/neorg/modules/core/gtd/ui/views_popup.lua
lua/neorg/modules/core/highlights/module.lua
lua/neorg/modules/core/looking-glass/module.lua
lua/neorg/modules/core/neorgcmd/commands/module/list/module.lua
lua/neorg/modules/core/neorgcmd/module.lua
lua/neorg/modules/core/norg/completion/module.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/esupports/hop/module.lua
lua/neorg/modules/core/norg/manoeuvre/module.lua
lua/neorg/modules/core/norg/qol/todo_items/module.lua
lua/neorg/modules/core/presenter/module.lua
lua/neorg/modules/core/queries/native/module.lua
lua/neorg/modules/core/syntax/module.lua
lua/neorg/modules/core/ui/module.lua
lua/neorg/modules/core/ui/text_popup.lua

I'm finally back from holiday! I have many changes that I'm making to Neorg and the way I'm developing it - I'll let everyone know in a reddit post tomorrow what exactly is changing.
In the meantime I've implemented `core.looking-glass`, a module that lets you open a Neorg code block in a different buffer!
I'm pretty proud of it, here's a video showcase:
https://user-images.githubusercontent.com/76052559/177871130-d025e071-1ecb-4107-b906-e9f293f0932d.mp4

[FEATURE]: `core.looking-glass`

---

lua/neorg/external/helpers.lua

The original function used `vim.treesitter.language.require_language` to find available TS parsers. This was very slow. On my system, the loop with this function took over 140ms (~155ms total). As well, there was a pointless use of `gmatch` to find the filetype name from parsed syntax files. This also meant that the table that stored found syntax files would have duplicated syntax files no matter what as `/usr/share/nvim/syntax/c.vim` and `~/.local/share/nvim/site/pack/packer/start/vim-c/syntax/c.vim` are clearly different files
This PR fixes performance by searching for TS parsers only using runtime files. As well, the extension-less filename is used to get rid of any duplication. After this PR, it only takes ~15ms in total to run this function
Fixes #515 
Addresses some concerns in #511

Language list performance improvement

---

lua/neorg/modules/core/norg/journal/module.lua

This implements the templates feature for journal, the templates are local to the workspace used.

feat(journal): implement template feature

---

lua/neorg/modules/core/export/markdown/module.lua

Part of #508
<details>
<summary>Neorg</summary>
```norg
@comment
a
multiline
comment
@end
```
</details>
<details>
<summary>Markdown</summary>
```markdown
```
</details>

feat(export.markdown): export multiline comments

---

lua/neorg/modules/core/keybinds/keybinds.lua

feat(keybinds): add toc and link keybinds

---

docgen/init.lua

fix(docs): update installation link

---

lua/neorg.lua
lua/neorg/config.lua

I think it would be nice to let the user enable or disable lazy loading

feat(config): add `lazy_loading` option

---

lua/neorg/modules/core/tangle/module.lua

After that you can use path like `~/foo/bar/baz`

fix(tangle): expand output path

---

lua/neorg/modules/core/ui/module.lua

fix(toc): fix highlights

---

queries/norg/highlights.scm

feat(highlights): add comment highlight

---

doc/neorg.norg

Hey,
I saw a small typo so just wanted to do a pull request. Thanks!

docs: minor typo

---

lua/neorg/modules.lua
lua/neorg/modules/core/neorgcmd/module.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/journal/module.lua
lua/neorg/modules/core/presenter/module.lua
lua/neorg/modules/core/promo/module.lua
lua/neorg/modules/core/ui/module.lua
lua/neorg/modules/core/upgrade/module.lua

This PR fixes [my issue](https://github.com/nvim-neorg/neorg/issues/670).

fix: set filetype when creating new norg buffer

---

lua/neorg/modules/core/norg/dirman/module.lua

Just found this little one while going through the code.

fix(docs): incorrect parameter type

---

doc/neorg.norg

Hopefully this fulfills the goals of the original link :sunglasses:

fix: Update links for the documentation

---

lua/neorg/modules/core/norg/journal/module.lua

Note: I'm using the stylua version compatible with lua 5.2 as stated in the CONTRIBUTING.md, but it is still changing the format of the document on parts of the code I didn't touch.
This should fix #725

fix: `:Neorg journal today` would fail on alternative path separators

---

lua/neorg/modules/core/ui/calendar.lua
lua/neorg/modules/core/ui/module.lua

This PR proposes a way to integrate various modes into the calendar.
There are two parts to this proposal. 
The first part is how to give the selected date / range back to the code that requested it. I propose an implementation that make use of callbacks. If a callback is passed to the `create_calendar` function as an option, that callback will be called when the current calendar mode decides to.
What do you think about this idea? Another alternative would be to use events, but for such a simple task, it seemed overkill. We could also have both, if needed, or a better system that I couldn't think of.
Here it is how to set a callback with the proposed code:
```lua
module.public.select_date({
callback = function(selected_date)
vim.pretty_print(selected_date)
end
})
```
The second part is …

ref(calendar): mode integration (WIP)

---

docgen/docgen.lua

fixes #548
just trying to close an easy open issue

fix(docgen):installation documentation link for wiki

---

lua/neorg/modules/core/export/markdown/module.lua

fix(export):markdown export for horizontal_line

---

lua/neorg/modules/core/promo/module.lua

Fixes https://github.com/nvim-neorg/neorg/issues/795 and https://github.com/nvim-neorg/neorg/issues/803 and https://github.com/nvim-neorg/neorg/issues/822

refactor(promo): rewrite module to fix several bugs

---

lua/neorg/modules/core/concealer/module.lua

related: https://github.com/nvim-neorg/neorg/pull/849

docs(concealer): mention nerd font dependency for concealer

---

lua/neorg/modules/core/esupports/metagen/module.lua

fix(metagen): update generation to use user config for `updated` tag

---

lua/neorg/modules/core/qol/todo_items/module.lua

Fixes https://github.com/nvim-neorg/neorg/issues/893.

fix(todo_items): don't look at child if parent is todo

---

lua/neorg/modules/core/promo/module.lua

concealer no longer needs to be notified

refactor(promo): remove notify concealer

---

lua/neorg/modules/core/qol/toc/module.lua

fix: On close of TOC, only delete buffer if it exists

---

README.md

https://github.com/codicocodes/neorg

docs: add usage badge to readme

---

lua/neorg/modules/core/completion/module.lua
lua/neorg/modules/core/syntax/module.lua

fix: Fetched get_language_list from utils

---

lua/neorg/modules/core/concealer/module.lua

fixes https://github.com/nvim-neorg/neorg/issues/998

fix(concealer): do not render missing node

---

lua/neorg/modules/core/tangle/module.lua

feat: add blank lines between tangled blocks

---

lua/neorg/modules/core/highlights/module.lua

fixes https://github.com/nvim-neorg/neorg/issues/1024

fix(highlights): always try to attach highlights when triggered

---

lua/neorg/modules/core/dirman/module.lua

fixes https://github.com/nvim-neorg/neorg/issues/1060

fix(dirman): correctly create nested directory

---

lua/neorg/modules/core/esupports/metagen/module.lua

resolves https://github.com/nvim-neorg/neorg/issues/1042

feat(metagen): more precise timestamp with HH:MM:SS and timezone

---

lua/neorg/modules/core/qol/toc/module.lua

fixes https://github.com/nvim-neorg/neorg/issues/1041

fix(toc): preserve heading hierarchy

---

lua/neorg/modules/core/concealer/module.lua

fixes https://github.com/nvim-neorg/neorg/discussions/1066

fix(concealer): don't rerender at `conceallevel` change when disabled

---

lua/neorg/modules/core/tempus/module.lua

EDIT: fixes https://github.com/nvim-neorg/neorg/issues/1059

fix(calendar): call `os.date` twice to generate correct weekday

---

README.md

For [neorg users](https://discord.com/channels/834325286664929280/834326555160608769/1148067195755175936) that are not neovim devs or debuggers.
Hopefully this caps the counterproductivity of configuring for productivity.

docs(README): add TLDR section

---

lua/neorg/core/modules.lua
lua/neorg/modules/core/concealer/module.lua

Fixes https://github.com/nvim-neorg/neorg/issues/863.

fix(config): fix config.custom

---

lua/neorg/modules/core/esupports/hop/module.lua

Temporarily mitigates https://github.com/wslutilities/wslu/issues/295 until it's fixed.

feat(hop): feed wslview with decoded link

---

lua/neorg/modules/core/keybinds/keybinds.lua

Added shortcuts to enter link-traverse mode.

feat(keyinds): add keybind for entering link traversal mode

---

lua/neorg/modules/core/concealer/module.lua

fixes https://github.com/nvim-neorg/neorg/issues/1180.

fix(concealer): do not render on range change if concealer is disabled

---

lua/neorg/modules/core/qol/toc/module.lua

The ToC vsplit window width is 1/2 of original window width by default.
With this PR, the vsplit width will be auto shrinked to the max (virtual) line length + 1 (for margin) if this is smaller than default.

feat(toc): auto shrink toc vsplit width upon creation

---

lua/neorg/modules/core/concealer/module.lua

Resolves https://github.com/nvim-neorg/neorg/issues/1189.

feat(concealer): conceal numeric footnote title to superscript 

---

doc/neorg.norg

Fix error regarding horizontal lines.

fix(neorg.norg): clarify horizontal line syntax

---

lua/neorg/modules/core/export/markdown/module.lua

fixes #1247
https://github.com/nvim-neorg/neorg/assets/43814863/b4bb48da-f7f0-4948-af8b-aec62a0d801a

fix(export): Fix metadata missing values when exported to markdown

---

README.md

https://github.com/nvim-neorg/neorg/pull/1245#discussion_r1435601420 was mistakenly marked as resolved.

doc: clarify font requirement in TL;DR

---

lua/neorg/core/config.lua

fix(config): add support for bsd operating systems

---

lua/neorg/modules/core/itero/module.lua

This question was asked in discord, and it's not answered in the docs

docs(itero): add the event so users can remap it

---

lua/neorg/modules/core/dirman/utils/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua

@vhyrro  this is the PR that I said wouldn't make a lot of sense. But these refactors don't break anything (I checked all the places where `expand_pathlib` is used, they're all fine), and they allow [this](https://github.com/benlubas/neorg-interim-ls) to work.
For context, that module used to be a PR to core, but I've since pivoted to making it it's own external module.

chore: refactor a few functions to allow for an external LSP module

---

lua/neorg/modules/core/text-objects/module.lua

Fixes an issue discussed in discord.
<details>
<summary>Bug Reproduction</summary>
1. Open the lua below as a file
2. source the file
3. `viH`
4. observe that the first line is not highlighted in full, just the newline is highlighted
5. `ggo<esc>dd` (add and remove a line below the first one
6. `viH` again
7. Observe that the first line is highlighted in full
```lua
-- this is some comment text
-- It's going to be highlighted
-- source this file to see the issue in action
-- don't alter that comment text, it's the target of highlights
vim.keymap.set({"o", "x"}, "iH", function()
vim.api.nvim_buf_set_mark(0, "<", 1, 28, {})
vim.api.nvim_buf_set_mark(0, ">", 3, 46, {})
vim.cmd("normal! gv")
end)
```
</details>
**This PR does:**
- Use the method from nvim-treesitter's TS-utils module, which …

fix(text-objects): node selection inconsistencies

---

lua/neorg/modules/core/looking-glass/module.lua
lua/neorg/modules/core/qol/toc/module.lua
lua/neorg/modules/core/ui/module.lua

I fixed the bug that I found in the last PR that still got merged despite the bug :P 
- `fixed_width` option for the ToC window
- `create_vsplit` refactor/update to make use of the new `nvim_open_win` functionality in 0.10.0
- Fixed logic for computing the ToC width
- You can configure the `toc` command to just open but not enter the window

Take two on the ToC changes

---

lua/neorg/modules/core/latex/renderer/module.lua

docs(latex-renderer): list required latex packages

---

lua/neorg/modules/core/completion/module.lua

lmk if you want me to tone down the self promo here. I'm not sure if I should include this example, or just document it in a generic way.
I'm biased, but I think it's good to have an officially recognized way to get completions without a completion plugin.

feat(completion): allow custom completion engines

---

lua/neorg/modules/core/esupports/metagen/module.lua

I thought that this made it into the last PR but I guess I never pushed it? Strange. Sorry about that.
fixes #1517

fix(metagen): proper iteration on metadata fields

---

lua/neorg/modules/core/dirman/module.lua
lua/neorg/modules/core/esupports/hop/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/itero/module.lua
lua/neorg/modules/core/looking-glass/module.lua
lua/neorg/modules/core/pivot/module.lua
lua/neorg/modules/core/presenter/module.lua
lua/neorg/modules/core/promo/module.lua
lua/neorg/modules/core/qol/todo_items/module.lua
lua/neorg/modules/core/tempus/module.lua

keybinds PR missed a ton of documentation

docs: document keybinds in modules that were missing them

---

lua/neorg/modules/core/summary/module.lua

Extract category / path args from generate_workspace_summary command. Tested with both strategies and it seems to work.

fix(summary): Fix #1624

---

lua/neorg/modules/core/tangle/module.lua

I thought that I already did this... but apparently not

fix: expand tangle paths

---

lua/neorg/modules/core/tangle/module.lua

You can now tangle to a subdir that doesn't exist

fix(tangle): create missing dirs

---

docgen/docgen.lua

Revert "ci: print statement debugging CI only failures is fun"

---

.github/workflows/gendoc.yml

See documentation at https://github.com/rhysd/action-setup-vim?tab=readme-ov-file#usage

Use stable neovim version for documentation generation

---

lua/neorg/modules/core/esupports/metagen/module.lua

fix: iter_matches returns list of nodes now

---

README.md

docs(README): explain lazy loading is not supported

---

queries/norg/folds.scm

why didn't I do this years ago

feat: foldable lists and ranged verbatim

---

lua/neorg/modules/core/export/markdown/module.lua

Export ranged tag markdown tables correctly in core.export.markdown
