ftdetect/norg.vim

> Worried about lazy loading? It's very hard to do properly because of the way Neovim handles filetypes. I'm planning on adding a PR with support for Neorg files to the Neovim core at some point. 
Support in core isn't necessary for this. You can just add ftdetect for norg format and it'll work .Package managers to execute ftdetect files for lazyloaded plugins too . Lua is suported in core for ftdetect but not all plugin managers have support yet. For example packer doesn't yet run lua ftdetect files for lazyloading . It's planned though https://github.com/wbthomason/packer.nvim/issues/403

feat: Add ftdetect for norg filetype

---

lua/neorg.lua

Right now if you `nvim test.norg` it opens up a new file and inserts the `@document.meta` at the top. Similarly, if you open nvim and then `:e existing_file.norg` it will do the same. However, if you open up nvim and `:e new_file.norg`, Neorg is not initialized and the file does not get the `@document.meta`

Boot up Neorg on Bufnew

---

docs/EXAMPLE.norg

I overhauled the example to be up-to-date with the `unstable` branch.
I also tried to make it a more easy-going and enjoyable read compared to the full spec.
Hopefully this helps in resolving issues like #55 and #79

Overhaul example.norg

---

docs/NFF-0.1-spec.md
lua/neorg/modules/core/norg/concealer/module.lua

Fixes the first two bugs described in #81.
This also adds the `€` sign to the list of punctuation as previously suggested on Discord.

Some concealing fixes

---

doc/neorg.norg
doc/tags

This help-page is essentially a copy of the `EXAMPLE.norg` file.
However, it is accompanied by a `tags` file which vim understands and
parses to extract help tags.
In the future, an automatic generation of this tags file will be added.
For now, we have to update it manually. But the flex we can achieve with
having norg-formatted help pages is definitely worth that! 💪

Basic neorg help-page

---

docs/NFF-0.1-spec.md
lua/neorg/modules/core/norg/concealer/module.lua

This adds support for concealing the link modifier, `:`. Since tree-sitter will not allow us to do concealing natively we will have to rely on our trusty Vim syntax regions defined via regexes anyways.
Right now, I implemented the link modifier regex to only require being suff- and prefixed with another markup modifier on the opening and closing link modifiers, respectively. However, this somewhat contradicts the current spec which requires a **non-whitespace character** in front of the opening modifier. However, I find that is a limitation because it will prevent e.g. the following: `This is :*im*:possible!`
I believe, that this is a not uncommon scenario so I am open for suggestions on how to rephrase the spec accordingly. I placed a temporary TODO comment at the relevant position of …

Conceal link modifier

---

lua/neorg/modules/core/defaults/module.lua
lua/neorg/modules/core/keybinds/default_keybinds.lua
lua/neorg/modules/core/norg/manoeuvre/module.lua
lua/neorg/modules/core/norg/qol/todo_items/module.lua

This PR makes TODO items bind themselves to each other and all in all makes them a lot more intelligent.
There's still a few issues that need fleshing out:
I'll be working on those bit by bit and will try to merge this branch as quickly  as possible. There's a lot that I have to track and do simultaneously but this one should be easy.

Add more intelligent TODO item toggling

---

lua/neorg/external/helpers.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/esupports/metagen/module.lua

This PR overhauls the concealer module to use TreeSitter queries and nodes to perform concealing rather than parsing the entire document line-by-line and attempting to do regex matches. Thanks to this the code is much smaller and also more flexible. It fixes #63 and is all round much more performant. Exciting stuff!

Overhaul the concealer to use TreeSitter

---

doc/neorg.norg
docs/EXAMPLE.norg
docs/NFF-0.1-spec.md
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/norg/concealer/module.lua
queries/norg/highlights.scm

Adds the horizontal line delimiting modifier, `___`, as discussed over on discord:
:warning: depends on https://github.com/nvim-neorg/tree-sitter-norg/pull/16

feat: horizontal lines

---

lua/neorg/modules/core/norg/concealer/module.lua

This is a proposal for concealing ordered lists. It works okayish for now but will require https://github.com/neovim/neovim/pull/9496 to be fully functional for deep nesting and to support all planned punctuation wrappers (e.g. `double_parenthesis`) and roman numerals (because these can become quite long).
<details>
<summary>Raw norg file</summary>
```
* Conceal ordered lists
~ First item
~ Second item
~~ Nested item
~~ Another nested item
~~~ Third level
~~~~ Forth level
~~~~~ Fifth level
~~~~~~ Sixth level
~~~ Continuation on third level
~ Continuation on First level
~~ starting a new nested level
~ yet another continuation
~~~ jumping directly to the third level
~~ and for some reason we now go to the second one 🤷
~ This is a new list because it is in a new paragraph
Concealing can be …
```

feat: conceal ordered lists

---

lua/neorg.lua
lua/neorg/modules/core/keybinds/default_keybinds.lua
lua/neorg/modules/core/keybinds/module.lua

I found a bug related to custom module config loading. Looks it doesn't work as expected
Another bug I've found is that neorg leader is not passed to `default_keybinds.lua`. It always loads default value (I can't say why, but looks lua saves reference to module.config.public on module load and doesn't use it's updated version). main branch doesn't have this problem because it uses `neorg_leader` as argument.

fix(modules): pass custom config to load_module

---

lua/neorg/modules/core/norg/dirman/module.lua

This is similar to 76a621f00b8f631879dd7b75d63c788b40171764.  Get_workspace_match is unable to match 
workspace directories containing special characters.  In my case, its hyphens.

Fix workspace matching

---

README.md

To allow lazy load work, might need to 
1) add filetype `neorg` (if init.lua set syntex&filetype detection to be off when launch neovim, or, in any case nvim failed to detect filetype for `neorg`)
2) manually load `treesitter` before setup `neorg`
I think this would solve most problems related to lazy loading. But please comment on if it still failed to work.

docs: update README regarding lazyload

---

lua/neorg/modules/core/norg/completion/module.lua

I'd like to enable completion for project tags for this [extension](https://github.com/esquires/neorg-gtd-project-tags) where the set of completions updates changes depending on changes that are made after load time (e.g., a user adds another project/subproject tag).  This small PR enables that to happen. You can see its use in the `add-completion` branch of the extension [here](https://github.com/esquires/neorg-gtd-project-tags/blob/add-completion/lua/neorg/modules/utilities/gtd-project-tags/module.lua#L34)

feat: add callback for completions

---

README.md

Didn't see this changed yet, felt it was important to mention

docs: update readme to mention regex fallback for codeblocks

---

lua/neorg/modules/core/gtd/queries/creators.lua
lua/neorg/modules/core/gtd/queries/modifiers.lua
lua/neorg/modules/core/gtd/queries/retrievers.lua
lua/neorg/modules/core/gtd/ui/selection_popups.lua
lua/neorg/modules/core/keybinds/default_keybinds.lua
lua/neorg/modules/core/queries/native/module.lua

This supersedes #259. Check out https://github.com/nvim-neorg/neorg/pull/259#issuecomment-1001768316 for more information

Gtd performance

---

lua/neorg/modules/core/gtd/ui/displayers.lua

get_by_var can return either {} or nil. Prior to this pull request the if statement could pass when `data == {}`

fix check for no data

---

lua/neorg/modules/core/norg/completion/module.lua

Neorg had slowed down a lot for me recently. This fixed the slowdown I observed (it was calling [this function](https://github.com/esquires/neorg-gtd-project-tags/blob/master/lua/neorg/modules/utilities/gtd-project-tags/module.lua#L41) in [gtd-project-tags](https://github.com/esquires/neorg-gtd-project-tags) every time text changed).
Prior to this commit, when completion_data.complete was a function it would be called every time text was changed. This calculation is unnecessary though when the regex does not match.
Related to #233

move ret_completions after check for match

---

doc/gtd.norg
lua/neorg/external/helpers.lua
lua/neorg/modules/core/gtd/base/module.lua
lua/neorg/modules/core/gtd/helpers/module.lua
lua/neorg/modules/core/gtd/queries/retrievers.lua
lua/neorg/modules/core/gtd/ui/capture_popup.lua
lua/neorg/modules/core/gtd/ui/displayers.lua
lua/neorg/modules/core/gtd/ui/helpers.lua
lua/neorg/modules/core/gtd/ui/module.lua
lua/neorg/modules/core/gtd/ui/views_popup.lua
lua/neorg/modules/core/presenter/module.lua
lua/neorg/modules/core/ui/module.lua

Hello ! 🥳
This is part of the discussion I had with @molleweide in #307.
The idea is summarized below:
> Because we can improve the views a little bit by: Adding a new view called Unprocessed.
It'll group every task or project that is not entirely processed. 
For a task to be entirely processed, it has to be visible. 
- If it's a task: by having one or more contexts 
- If it's a project: by having one or more tasks associated.
In this way, we can remove the inbox file because we could view our unprocessed tasks, and we will not lose any tasks from the views.
In fact, I'm sure it'll be a better feature, because the inbox file is quite difficult to grasp for new users, and still not very usable by advanced users (because moving tasks and projects is not yet implemented in GTD actions).
I …

Unprocessed tasks logic

---

README.md

👋 
I was checking out this great project and wanted to jump to various parts of the README but the anchor links are broken. Looks like the markdown parser strips emojis. So this removes the emojis from the links at the top of the README.
Example: https://github.com/nvim-neorg/neorg#-showcase
Thanks 💖

docs: update anchor links in README

---

lua/neorg/modules/core/ui/module.lua

This allows autocommands to be specified like this
```
au FileType neorg ...
```
Note that this is for neorg, not norg, buffers

feat(ui): add filetype to create_(v)split

---

lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/concealer/preset_brave.lua
lua/neorg/modules/core/norg/concealer/preset_dimmed.lua
lua/neorg/modules/core/norg/concealer/preset_safe.lua

This PR is a temporary workaround for treesitter based concealing not working (see https://github.com/nvim-neorg/neorg/issues/292#issuecomment-1073023644). The "brave" preset will now actually physically conceal the text thanks to a discovery I made recently with `matchaddpos()` :P
It may be a little less performant with this update, but it's a tradeoff I'm willing to make until we get the real thing.

Treesitter Based Concealing

---

lua/neorg/modules/core/gtd/ui/capture_popup.lua

contexts and waiting for now has current values as default text so you can edit them

add default text for capture popup

---

doc/neorg.norg

Just found a minor typo in the documented presented by :h neorg.
I hope that such formally lacking PRs are welcome.
Note: No code changes

docs: minor typo

---

lua/neorg/modules/core/export/module.lua

My Pop OS machine would fail to run the export function, complaining that arg 3 of vim.loop.fs_write is nil instead of a number. Using 0 instead seems to remedy this. My Arch machine works fine

fix: errors in fs_write on some systems when exporting a file

---

lua/neorg/modules/core/norg/esupports/indent/module.lua
lua/neorg/modules/core/queries/native/module.lua

Prior to this pull request, `query_nodes_from_buf` could return `{}` or `nil`. When it was the latter, this block in `retrievers.lua` in the `get` function would fail:
```lua
for _, bufnr in pairs(bufnrs) do
---@type core.queries.native
local queries = module.required["core.queries.native"]
local nodes = queries.query_nodes_from_buf(tree, bufnr)
vim.list_extend(res, nodes)  -- fails here because nodes is nil
end
```
The backtrace is 
```
Error executing vim.schedule lua callback: vim/shared.lua:0: src: expected table, got nil
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'validate'
vim/shared.lua: in function 'list_extend'
.../neorg/lua/neorg/modules/core/gtd/queries/retrievers.lua:104: in function 'get'
```

fix(gtd): nil query

---

lua/neorg/modules/core/norg/concealer/module.lua

This PR actually fixes issue #432 by using recursion to iterate over all descendant nodes and counting all todo_items.

fix: concealer breakage on carryover tag set when calculating todo items

---

lua/neorg/modules/core/norg/esupports/hop/module.lua

First, thank you for your efforts in this project, `neorg` works great for me so far!
However, a major pain point I encountered while using `neorg` is that external links are currently opened synchronously via a simple call to `vim.cmd("xdg-open [...]")`; so when I follow a link to a website inside `neorg`, it will open my browser and then block until the browser is closed. I see a lot of potential in `neorg` for organizing references to websites and local files, but I think this behaviour makes it frankly unusable for this purpose and I don't think this behaviour is what most users would expect or want.
This PR proposes to instead spawn the processes used to open external links via `luvit` in an asynchronous manner; since `neorg` already uses/depends on `plenary.nvim`, this change comes …

feat(hop): open external links asynchronously

---

lua/neorg/modules/core/neorgcmd/module.lua

First of, I realised that I should maybe have first reach out and checked if this makes sense with the current vision. But you can see this more as a draft/suggestion and if you don't like it no problem :)
I started trying out `neorg` a few days ago and already loving it. When starting out one thing that bothered me a bit was when I was trying to run a command, let's say `:Neorg news` just to see what it does, I get an error with something like:
```
Unable to execute neorg command under name event_name - minimum argument count not satisfied. The command requires at least
```
of course I can then try again using `<Tab>` so see what the options are. But to reduce that little bit of friction I thought it would be great if instead of giving the error, `neorg` would instead query the user for …

feat(neorgcmd): select next unspecified command argument

---

lua/neorg/external/helpers.lua
lua/neorg/modules/core/defaults/module.lua
lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/tangle/module.lua

It is time :D
This PR adds basic tangling support for Neorg (only for the currently open file). For proper documentation I recommend you consult the wiki entry. I'll copy paste it here for reference:
The goal of this module is to allow users to spit out the contents of code blocks into
many different files. This is the primary component required for a literate configuration in Neorg.
- `:Neorg tangle current-file` - performs all possible tangling operations on the current file
By default, *zero* code blocks are tangled. You must provide where you'd like to tangle each code block manually (we'll get to global configuration later).
To do so, add a `#tangle <output-file>` tag above the code block you'd wish to export. For example:
```norg
#tangle init.lua
@code lua
print("Hello World!")
@end …
```

feat: add `core.tangle`

---

lua/neorg/modules/core/export/markdown/module.lua

Hi! If you export a link using non-ASCII characters, you will get an empty link.
<details>
<summary>Neorg file</summary>
```norg
* что-то, на. русском!!
{* что-то на русском}
```
</details>
<details>
<summary>Before</summary>
```md
[что-то на русском](#-)
```
</details>
<details>
<summary>After</summary>
```md
[что-то на русском](#что-то-на-русском)
```
</details>

fix(export.markdown): properly format markdown links

---

lua/neorg/modules/core/export/markdown/module.lua

If you export a code with tangle to markdown, you will get an incorrect result.
<details>
<summary>Neorg file</summary>
```norg
#tangle test.lua
@code lua
print("Hello World!")
@end
```
</details>
<details>
<summary>Before</summary>
````md
test.lua```lua
print("Hello World!")
```
````
</details>
<details>
<summary>After</summary>
````md
```lua
print("Hello World!")
```
````
</details>

fix(export.markdown): properly export tangle

---

lua/neorg/modules/core/export/markdown/module.lua

If you export a `.norg` file with multiple paragraphs to markdown, you will get incorrect paragraph breaks.
<details>
<summary>Neorg file</summary>
```norg
123
456
789
```
</details>
<details>
<summary>Before</summary>
```md
123
456
789
```
</details>
<details>
<summary>After</summary>
```md
123
456
789
```
</details>

fix(export.markdown): paragraph breaks

---

lua/neorg/modules/core/norg/qol/toc/module.lua

This PR does two things to TOC module:
1. use `lib.match` for toc events (and that simplifies readability)
2. allow keybinds only on toc buffer

Fix toc keybinds

---

lua/neorg/modules/core/gtd/helpers/module.lua

I noticed a bug when trying to view the project view in GTD. It seems that the helper was improperly mapping state to `onhold` rather than `on_hold`, as it's seen everywhere else in the codebase.

fix: fix state_to_text translation for gtd

---

lua/neorg/modules/core/export/markdown/module.lua

Part of #508
Neorg:
```norg
A link without description: {www.wikipedia.org}
```
Before:
```markdown
A link without description: [](www.wikipedia.org)
```
After:
```markdown
A link without description: [www.wikipedia.org](www.wikipedia.org)
```

fix(export.markdown): always save last parsed link

---

lua/neorg/modules/core/export/module.lua

fix(export): using `vim.fn.expand` for path (fixes #540)

---

lua/neorg/modules/core/export/markdown/module.lua
lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua

Part of #508
<details>
<summary>Neorg</summary>
```norg
@document.meta
title: test
description:
categories: [
this
that
]
created: 2022-07-10
version: 0.0.11
@end
```
</details>
<details>
<summary>Before</summary>
```markdown
---
title: test
description:
categories: [
this
that
]
created: 2022-07-10
version: 0.0.11
---
```
</details>
<details>
<summary>After</summary>
```markdown
---
title: test
description:
categories:
- this
- that
created: 2022-07-10
version: 0.0.11
---
```
</details>

fix(export): export correct yaml metadata

---

lua/neorg/modules/core/export/markdown/module.lua
lua/neorg/modules/core/looking-glass/module.lua
lua/neorg/modules/core/norg/completion/module.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/syntax/module.lua
queries/norg/injections.scm

New feature: export of code blocks. See example:
```norg
* Test title
@export markdown
**bold** *italic*
<h3>Test subtitle</h3>
@end
@export latex
I don't want to export it to markdown
@end
*bold* /italic/
```
```markdown
**bold** *italic*
<h3>Test subtitle</h3>
**bold** _italic_
```

feat(export): export code blocks

---

lua/neorg/modules/core/highlights/module.lua
queries/norg/highlights.scm

feat(highlights): add multiline comments highlight

---

lua/neorg/modules/core/ui/module.lua

Fixed the error that occurred when following a link in toc:
```
Error executing vim.schedule lua callback: ...org/lua/neorg/modules/core/norg/esupports/hop/module.lua:206: attempt to index local 'node_under_cursor' (a nil value)
```

fix(core.ui): filetype `neorg` -> `norg`

---

lua/neorg/modules/core/norg/esupports/hop/module.lua

Windows' `start` is shell builtin of `cmd.exe` and not an executable, which makes it unusable by `plenary.nvim`'s job module. It also has some strange behavior like launching a new shell instead of properly opening the link if the user surrounds the link in quotes, so I've just decided to instead directly call `url.dll` with `rundll32.exe` (Netrw's `gx` also uses this).

fix(hop): open external links in Windows

---

lua/neorg/modules/core/norg/journal/module.lua

Using `:Neorg journal toc`, a TOC file will be created inside the journal folder which links to all entries, the format for the toc file is configurable with a user made function (see example)
Basically, just use the journal module however you want, and whenever you wish to see all your entries, just call the command and the file will be created (and updated)

feat(journal): create a toc from all the journal entries

---

lua/neorg/modules/core/export/markdown/module.lua
lua/neorg/modules/core/export/module.lua

I think using tables instead of a list of values will improve extensibility

refactor(export): return table instead values

---

lua/neorg/modules/core/highlights/module.lua
lua/neorg/modules/core/norg/esupports/metagen/module.lua
queries/norg_meta/highlights.scm

This PR aims to add a new field to default document metadata template called `updated` that serves as a last updated field for norg documents.
That field gets automatically updated on `BufWritePre` event if current date is different from last updated date from said field.
Edit: also updated `neorg.modules.core.norg.esupports.metagen.module` to use `module.required["core.neorgcmd"].add_commands_from_table()` for creating `:Neorg` commands as discussed on discord server.

feat(meta): add a new updated field to document metadata

---

README.md
lua/neorg/config.lua
lua/neorg/modules.lua
lua/neorg/modules/core/export/markdown/module.lua
lua/neorg/modules/core/highlights/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/neorgcmd/module.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/esupports/metagen/module.lua
lua/neorg/modules/core/syntax/module.lua

It's time for some changes. Yes, they are breaking changes, I know nobody likes them, but here they are definitely for the better.
If you don't like the change, feel free to use this configuration:
```lua
require("neorg").setup {
lazy_loading = true,
load = { ... },
}
```
- `:NeorgStart` no longer exists and you always have access to a `:Neorg` command
- Highlights are always active, which means that e.g. highlights in telescope previews work now
- Some commands will error out if you use them outside of a `.norg` file
- Your config's startup time will be increased by just under 30 milliseconds (on my hardware at least)
- Apart from reenabling the `lazy_loading` flag, you can also lazy load using your plugin manager via e.g. the `ft = "norg"` flag in packer.
- Work will be done to optimize …

feat: disable lazy loading by default

---

lua/neorg/modules/core/tangle/module.lua

Let's say we need to tangle the `norg` code (with escape char `\`):
```norg
+a.norg+
#tangle b.norg
@code norg
\@math
123 + 456
\@end
@end
```
Without this patch you will get:
```norg
+b.norg+
\@math
123 + 456
\@end
```
After this patch you will get:
```norg
+b.norg+
@math
123 + 456
@end
```

feat(tangle): properly tangle escaped norg code

---

lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/gtd/base/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/keybinds/module.lua
lua/neorg/modules/core/mode/module.lua
lua/neorg/modules/core/neorgcmd/commands/module/list/module.lua
lua/neorg/modules/core/neorgcmd/commands/module/load/module.lua
lua/neorg/modules/core/neorgcmd/commands/return/module.lua
lua/neorg/modules/core/neorgcmd/module.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/dirman/module.lua
lua/neorg/modules/core/norg/esupports/metagen/module.lua
lua/neorg/modules/core/norg/journal/module.lua
lua/neorg/modules/core/norg/news/module.lua
lua/neorg/modules/core/norg/qol/toc/module.lua
lua/neorg/modules/core/presenter/module.lua
lua/neorg/modules/core/tangle/module.lua

After a long wait, I decided it was time to rewrite this module to open up some more possibilities.
Here are some things that this improves:
- Uses Lua APIs to define commands. There's a noticeable speed difference when executing commands, it's much snappier.
- The table used to define commands has been changed to something much simpler. No more `definitions` and `data` tables!
- Added a `complete` argument for commands that want more complex completion for parameters
- **Added a `condition` command that can allow for conditional command execution**.
This is the big one - now that Neorg is no longer lazy loaded by default it would be great to have more commands related to workflow, but nobody wants to see a load of commands in their completion popup! If you're in a `.norg` file, then …

feat: rewrite `core.neorgcmd` module

---

lua/neorg/modules/core/norg/concealer/module.lua

Fixes #600.
Are there other file types that the concealer should automatically attach to on the this auto command?

fix(concealer): Don't attach to non-norg buffers.

---

doc/neorg.norg

Commit c5345e72ebdd84585eec6272755aa26233431317 removed the specification file from this repository so the link at the start of `:h neorg` 404s. This commit changes to link to point to the specification directory.

docs: update link to specification file

---

lua/neorg/modules/core/integrations/treesitter/module.lua

The implementation of the actions that allow you to jump to the next or previous heading/link contains a small bug that causes the matching node on the next line to be skipped. It also ignores matching nodes that occur after the cursor on the same line.
Fixes #609

fix: jump to next/prev headings or links

---

lua/neorg/modules/core/norg/concealer/module.lua

I think adaptive should be disable when conceal not enable.
Otherwise the behavior when { adaptive = true, conceal = false } kinda weird (only background adaptive).

fix(concealer): don't update `content_only` variable if `conceal` is false and `adaptive` is true

---

lua/neorg/modules/core/tangle/module.lua

For example, I want to tangle two files
Before:
```
Successfully tangled 1 file!
Successfully tangled 1 file!
```
After:
```
Successfully tangled 2 file!
```

fix(tangle): show correct tangled count

---

README.md

Under the installation instructions, it says Neovim 0.8+ is required to operate, but the link at the top of the README is still showing 0.7+.

docs(README): update Neovim icon to 0.8+

---

lua/neorg/modules/core/norg/esupports/hop/module.lua

Noticed that non-norg file links were completely broken. The issue was a bad string match when trying to find the file type, as well as `vim.cmd` not working correctly
This fixes it by using `vim.fn.fnamemodify` to directly get the file paths desired as well as replacing `vim.cmd` with `vim.api.nvim_exec` for the hop file edit call

fix: broken link following when using hop

---

lua/neorg/modules/core/integrations/treesitter/module.lua

Anchor definitions and anchor declarations were skipped when jumping to the next or previous link. This was a bit surprising as you could jump to links with a custom text for example. Since anchors serve a similar purpose as links, it makes sense to be able to jump to them.
To test this, use the same Neorg setup as described in issue #609, then create a new norg file with the following contents:
```
{:link1:}
{:link2:}[description]
[anchor]
[anchor]{:link3:}
{:link4:}
```
With the cursor on the first line, repeatedly press `Tab`.

fix: do not skip anchors when jumping to next/prev link

---

queries/norg/highlights.scm

- Fixes https://github.com/nvim-neorg/neorg/issues/642  ; https://github.com/folke/todo-comments.nvim/issues/106
- Original commit: https://github.com/nvim-neorg/neorg/commit/887dc41f508aea1d1c9f195dba18a3aac0a2e1c8

fix: `folke/todo-comments.nvim` comment highlighting in `.norg` files

---

lua/neorg/modules/core/norg/concealer/module.lua

Currently if you open a `norg` file first and folding is enabled, fold options will be set on the window globally. So any buffer you open afterwards will apply folding even if it's not a norg file.
If we use `nvim_set_option_value` and use `scope = local` the fold options will only apply locally to the buffer
```
*nvim_set_option_value()*
nvim_set_option_value({name}, {value}, {*opts})
Sets the value of an option. The behavior of this function matches that of
|:set|: for global-local options, both the global and local value are set
unless otherwise specified with {scope}.
Note the options {win} and {buf} cannot be used together.
Parameters: ~
{name}   Option name
{value}  New option value
{opts}   Optional parameters
• scope: One of 'global' or 'local'. Analogous to
|:setglobal| and …
```

fix(concealer): set win local fold options

---

lua/neorg/modules/core/defaults/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/itero/module.lua
lua/neorg/modules/core/keybinds/keybinds.lua

This module handles item continuation, like continuation of lists, quotes, headings etc.
`<CR>` in insert mode will *not* continue the current line, like you would expect it to. By default, `<M-CR>` (Alt + `<CR>`) continues the current item. This is a big contrast to the "traditional way", as the Neorg behaviour is *opt in* vs *opt out*. I have a few reasons as to why this is a much better solution, including less fighting with the editor, no ambiguous behaviours on when to continue and item and when not to, etc.
Let me know what you think of it and optionally submit bug reports or feature requests! :)

feat: add `core.itero` module

---

lua/neorg/modules/core/clipboard/code-blocks/module.lua
lua/neorg/modules/core/clipboard/module.lua
lua/neorg/modules/core/defaults/module.lua
lua/neorg/modules/core/keybinds/keybinds.lua

This module is specifically designed for interacting with the clipboard. @xfzv this one's for you :p
This PR comes with a bonus module: `core.clipboard.code-blocks`, which removes the indentation whenever you copy the content of a code block. Makes for pasting code snippets e.g. on discord very easy.
Future TODOs may include:
Still a little buggy with some weird edge cases with blocks selection and regular visual selection - those will be fleshed out as time passes :). Linewise visual selection works great!

feat: add `core.clipboard` module

---

lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/norg/qol/toc/module.lua
lua/neorg/modules/core/ui/module.lua

This PR entirely rewrites the TOC module and improves its performance and some behaviours:
- The TOC now updates on any buffers changes
- If you change to another `.norg` buffer, the TOC will also update accordingly
- The `.TOC` tag is no longer mandatory to open up a table of contents, but can be used to change the TOC title if you so wish
- Very solid performance improvements across the board

ref(toc)!: refactor the `core.norg.qol.toc` implementation

---

lua/neorg/modules/core/integrations/nvim-cmp/module.lua
lua/neorg/modules/core/norg/completion/module.lua

Added the "(" as a trigger character, prevent ( from spawning a ) with the updated regex and updated the completion table.
I'm not super familiar with the new syntax yet.. or the syntax in general; so I'll probably end up reading up on the documentation to see what other completions can be disregarded and what completions should be added. But I'll do that in a future pull request.

fix: completion for TODO items

---

lua/neorg/modules/core/norg/journal/module.lua

the failure in generating the journal TOC came from assuming that the
user's current workspace is the journal's workspace, which may not be
true if a journal has a workspace set in the configuration. 
i tested with my config so it fixes the bug, the changes are small so hopefully no bugs were created

fix(core.norg.journal): fixes #736 , now generates TOC correctly

---

lua/neorg/modules/core/norg/dirman/module.lua

- Allow users to use the vim's default input prompt in cmdline instead of popup prompt provided by neorg ui when creating a new note

feat(dirman): add new `use_popup` option for `dirman`

---

lua/neorg/modules/core/ui/module.lua

- Use `vim.fn.winheight` ,`vim.fn.winwidth` instead of `vim.opt_local.lines:get()` and `vim.opt_local.columns:get()` to calculate the correct window size.
- Note that `vim.opt_local.{cols,lines}` don't take account split panes and extra spaces such as `winbar`, `statusline` and `cmdheight`

fix(dirman): corrected win width and height calculation

---

lua/neorg/modules/core/norg/dirman/module.lua
lua/neorg/modules/core/norg/dirman/summary/module.lua

it took me way too long to do this, really lost all my lua skills. there are various ways to improve but for a first version i think it is good. this code is probably undercommented, so if anything is unclear please ask.
possible improvements,
- allow user to configure which heading gets the summary
- allow user to configure which file gets the summary
- filter files by metadata
- move query logic to core.queries and make a new function there
- add a comment that gron. substitution is to allow files like xx.norg.norg
- expose some logic as lua functions
- make calling :Neorg generate-workspace-summary also call :w
- make the links relative to workspace root so they work for files in subdirectories
as this is around 100 lines i opted for implementing only generating the summary for now.

feat: add `dirman.summary` module

---

docgen/docgen.lua
lua/neorg/external/helpers.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/looking-glass/module.lua
lua/neorg/modules/core/norg/concealer/module.lua
lua/neorg/modules/core/norg/dirman/summary/module.lua
lua/neorg/modules/core/norg/esupports/hop/module.lua
lua/neorg/modules/core/norg/esupports/metagen/module.lua
lua/neorg/modules/core/syntax/module.lua
lua/neorg/modules/core/tangle/module.lua

Hello everyone,
neovim 0.9 deprecated the `vim.treesitter.parse_query` call a few days ago.
You should now use `vim.treesitter.query.parse` instead.
I introduced a new `neorg.utils.ts_parse_query` function that will check the
neovim version used and use the right call. I replaced all usage of `parse_query`
with the new function.
Have a great day everyone!

fix: neovim 0.9 vim.treesitter.parse_query deprecation

---

lua/neorg/modules/core/ui/calendar.lua

This fixes the issue that I've talked about recently (when the current date is higher than the previous/following month max day)
It also contains an improvement for the leap year check.

ref(calendar): extract logic, fix bug with time reformatting

---

lua/neorg/modules/core/ui/calendar.lua

This commit completes the extraction of the rendering logic out of the `create_calendar` function. This allows us to re-render the view sections as needed without too much extra code. It also simplifies the keybindings logic, and allowed the easy integration of "j" and "k" keybindings, which goes to the previous and next week, respectively.
The new keybinding logic also fixes an issue with leap years. Previously, if the month of february was rendered with 29 days, and then we moved to a different year where february only had 28 days, it would break the logic and not render correctly.

ref(calendar): extract rendering logic, add and improve keybinds

---

lua/neorg/modules/core/ui/calendar.lua

This PR is mainly aimed at fixing the calendar when the view is too small to show more than one month. Currently, this is breaking the code because other months extmarks are not removed and will be displayed on top of the visible ones.
I've added a function to clear the extmarks of the months that are outside of the current view, and this fixes the issue.
The visible months are now limited to 11 (the center one + 5 on the sides) because having more than 12 months will break a lot of the current code.
I've also slightly refactored the extmark creation functions to make them more DRY.

ref(calendar): refactored extmark creation, fixed single month view and added month limit

---

lua/neorg/modules/core/norg/qol/toc/module.lua

This PR adds an option to close the table of contents buffer after an entry has been chosen. It's `false` by default.

feat(toc): add `close_after_use` configuration option (#785)

---

lua/neorg/modules/core/export/markdown/module.lua

Hi, thanks for the nice plugin!
As I mentioned in #807, several characters in links inside exported markdown files are escaped and do not link to the desired position.
Several examples are...
- `{https://www.youtube.com/watch?v=j4lTvIGRhmw}["?" => "%3f"]`
- ["?" => "%3f"](https://www.youtube.com/watch%3fv=j4lTvIGRhmw)
- `{https://github.com/nvim-neorg/neorg/#-installationquickstart}["#" => "%23"]`
- ["#" => "%23"](https://github.com/nvim-neorg/neorg/%23-installationquickstart)
where if you follow the links above, they do not jump to the correct link, due to the conversion.
This PR aims to fix / workaround the output from `vim.uri_from_fname()` to fix this issue.
Hope this helps.
Best,

fix(export): `gsub` export links that contain `#`, `?`. closes #807

---

ftdetect/norg.lua
ftdetect/norg.vim

This PR aims to modernize old VimL files to use Lua files with the Neovim Lua API,
also because I hate Vim Script.

ref!(ftdetect): rewrite filetype detection logic from VimL to Lua

---

lua/neorg/modules/core/concealer/module.lua

Many potential causes for buffer to be unloaded, but `:h vimgrep` is a big one. Without this fix, `:vimgrep` can get caught in an infinite loop of errors because the concealer wants to keep going until everything is done, but that can not happen if `:vimgrep` does not find a match and immediately deletes the buffer.

fix(concealer): stop concealer if buffer is not loaded

---

docgen/docgen.lua
res/wiki/static/Dependencies.md

Per our discussion in the discord, this PR creates a Dependencies.md which describes the dependencies and some of the many pitfalls involved in getting the basic Neovim + Terminal things set up correctly.
It also (messily, perhaps), creates a subfolder `res/wiki/static` in which files can be placed and which will get copied into the wiki. I haven't had a chance to test that this works properly, so it definitely needs appropriate review before it gets merged.

docs: add Dependencies.md

---

lua/neorg/modules/core/ui/calendar/module.lua
lua/neorg/modules/core/ui/calendar/views/monthly.lua
lua/neorg/modules/core/ui/module.lua

This very small PR presents a fix for the distance option that gets passed to the monthly view. It also improves a little on code readability in that function.

ref(calendar): implemented distance (monthly view) and run make format

---

lua/neorg/modules/core/concealer/module.lua
lua/neorg/modules/core/syntax/module.lua

Ran into the syntax processing infinite recursion when running `:Neorg generate-workspace summary`. Same issue as with `:vimgrep` when buffers are rapidly opened/closed and there is async happening.
Also rolled in the changes on `block_current` calculation.

fix: stop syntax processing if a buffer is already closed

---

lua/neorg/modules/core/concealer/module.lua

The icons used to conceal 'done' and 'pending' tasks were [moved to new code points](https://github.com/ryanoasis/nerd-fonts/blob/master/changelog.md#breaking-2-material-design-icons-codepoints). This commit fixes them according to [this translation table](https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287).

refactor: use new icons for `done`/`undone` as per nerd fonts 3.0

---

lua/neorg/modules/core/tempus/module.lua

When trying to insert a date from the calendar view the wrong weekday is shown. The problem is that `os.date("*t")` returns `wday` with Sunday as 1, while the `weekday` names in the tempus module assume Monday as 1.

fix(tempus): paste correct weekday from calendar

---

README.md

Fix the documentation for #74, required C++11 instead of C++14, took me quite a while in the issue section

docs(README): add treesitter fix for macos

---

lua/neorg/modules/core/integrations/treesitter/module.lua

I've noticed #887 and figured maybe we can do a bit bitter.
Pointing people at installing external c++ compilers like gcc (especially via homebrew which they may not be using) in order to use neorg is not the most welcoming thing to put in a readme 🙂
(Also note that the "point CC at a compiler with C++11 support" part of the readme is not entirely incorrect, because native `clang` _does_ have C++11 support; it's just not the default.)
Here's a solution that I've tested myself on two different macOS boxes, does _**not**_ require any additional dependencies and should work with system-provided `clang`.
This did require digging a bit into treesitter installer internals (unfortunately) so it may potential break with future treesitter releases, however that part of TS didn't seem to have …

fix: TSInstall issues on macOS, hopefully once and for good

---

lua/neorg/modules/core/esupports/hop/module.lua

Fixed example: `{/ ~/.vimrc|echo "Hello"}[injection]`

fix(esupports): use structured api to avoid injection

---

lua/neorg/modules/core/keybinds/keybinds.lua
lua/neorg/modules/core/qol/todo_items/module.lua

The 1.0 spec https://github.com/nvim-neorg/norg-specs/blob/main/1.0-specification.norg including "need input" todo status:
https://github.com/nvim-neorg/norg-specs/blob/f4d696ebfe9c227fc912ad4249c6b34f71f4ace4/1.0-specification.norg#L573
But the current module do not include this status so I create this PR.

feat(todo-items): add missing "need input" icon and action

---

lua/neorg/modules/core/esupports/hop/module.lua

- Some refactoring.
- Made `{line}` links work.
- Made `{:file:line}` links work.
- Made `{/ file:line}` links work.
- Made `{/ file}` links respect split option.
- When opening external or calendar links with split option, no longer opens unnecessary splits/tabs.

feat(esupports.hop): link jump to line + fixes + refactoring

---

lua/neorg/modules/core/itero/module.lua

Resolves https://github.com/nvim-neorg/neorg/issues/910.

feat(itero): don't start newline on empty line

---

lua/neorg/modules/core/highlights/module.lua

This stops the propagation of highlighting problems caused by packer lazy loading (`ft = "norg"`)

fix(highlights): assert on treesitter being enabled

---

lua/neorg/modules/core/concealer/module.lua

- change `to_eol and nil or {...}` to `not to_eol and {...} or nil`, because `A and nil or B` always results in just `B`.
- add the to_eol optimization to the `len < start` case
- fix the following case
```
*** try with `padding = { left = 2 }, width = "content"`
@code lua
a
@end
```

fix(concealer): minor fixes, plus wiki error fix

---

README.md

Using ```config = function()``` is generally preferred over using ```opt```, so the section for lazy.nvim should be using 
```config = function()``` instead of ```opt```

docs(README): make lazy.nvim install instructions more standard

---

lua/neorg/modules/core/concealer/module.lua

fixes concealing in `[anchor]{* definition}`
fixes https://github.com/nvim-neorg/neorg/issues/922

fix(concealer): fix concealing in anchors, don't error on broken config

---

lua/neorg/modules/core/concealer/module.lua

This is a WIP PR to add anticonceal support to the concealer.
To implement this, the `multilevel_ordered_inline_on_right` renderer takes in a `generator(number) -> string` in its config. This is then passed to a `formatters` list, which are a list of lua patterns to format each level of ordered list. Currently only a default `tostring` generator is supported.
It's super satisfying to see work in realtime :p
Things to work on:

feat(concealer): add numeric anticonceal if supported

---

lua/neorg/modules/core/summary/module.lua

A few bugfixes & added flexibility, after trying to use `:Neorg generate-workspace-summary` on my workspace.
> * Currently the `metadata` strategy is making assumptions about the metadata in your doc, and failing with an error if specific key is not present.
>     * e.g. if you `:Neorg inject-metadata` and your metadata doesn't specify a `description` or `categories`, then it just errors. 
>     * If you don't have a `title`, you get nothing. 
>     * It also doesn't like numeric titles like in a journal, e.g. I had `06` for 6th May. It fails in this case too.
>
> * The generated summary always uses a **  heading regardless of what level of heading your cursor is on.
> * If you have inconsistent title casing in your metadata categories, the alphabetic ordering doesn't work (even though …

fix(core.summary): bugs + flexibility around incomplete metadata

---

lua/neorg/modules/core/keybinds/keybinds.lua
lua/neorg/modules/core/keybinds/module.lua

this is to support proper desc= options for which-key, not clear if this is the right place to do this or not. I also don't like setting opts = defaults in the loop but i couldn't think of another way with out changing the rest of the code.

feat(keybinds.lua): add `desc` fields to task keybinds

---

lua/neorg/modules/core/summary/module.lua

Fixes and improvements following on from https://github.com/nvim-neorg/neorg/pull/927 . I noticed a bug in the link destinations, so I went ahead and did some of what @vhyrro suggested.
My summary looks like this now (as before, I only have scraps of document metadata, and some files are completely empty):
```norg
** My Heading Which My Cursor Was On
*** Homebase
- {:index:}[Work Notes]
*** Uncategorised
- {:help:}[Help]
- {:inbox:}[Inbox]
- {:main:}[Neorg Notes]
- {:neorg:}[Neorg Adventures]
- {:nostuff:}[Nostuff]
- {:projects:}[Projects - Medium Term]
- {:journal/index:}[2023]
- {:journal/template:}[Template]
- {:journal/2023/05/04:}[04]
- {:journal/2023/05/05:}[05 Tues]
- {:journal/2023/05/06:}[6]
- {:journal/2023/05/07:}[7]
- {:journal/2023/05/08:}[8]
- {:journal/2023/05/18:}[18]
```

fix(summary)!: fix norg links, use first heading as title if found

---

lua/neorg/modules/core/concealer/module.lua

This fixes an assertion error triggered by prefixes not followed by text (try `i~ <CR>`).

fix(concealer): disable assertion for prefixes until parser changes

---

lua/neorg/modules/core/ui/calendar/module.lua

This commit changes the logic for creating the calendar window to always request at least the minimum size necessary to render the full calendar. Previously, a window size could be created even though it was too small to render the calendar.

fix(calendar): give calendar enough space to render

---

lua/neorg/modules/core/ui/module.lua

Hello everyone! Thanks for great plugin. I tried to fix this in config by using autocmds, but couldn't make it work, so I decided to make this PR, I believe this is sensible default for UI window
**Before:**
**After:**

fix(ui): remove possible ui noise caused by user's opts

---

lua/neorg/config.lua
lua/neorg/external/helpers.lua
lua/neorg/modules/core/esupports/hop/module.lua

Use Neovim with this plugin in Windows Subsystem for Linux (WSL)
1. Create a hyperlink in `.norg` file , e.g.  "{https://github.com}[GitHub]"
2. Move cursor to the hyperlink
3. Press Key **[Enter]**
An error occured:
```
stack traceback:
[C]: in function 'error'
...nvim/site/pack/lazy/opt/plenary.nvim/lua/plenary/job.lua:106: in function 'new'
...pt/neorg/lua/neorg/modules/core/esupports/hop/module.lua:94: in function 'os_open_link'
...pt/neorg/lua/neorg/modules/core/esupports/hop/module.lua:122: in function <...pt/neorg/lua/neorg/modules/core/esupports/hop/module.lua:121>
```
Link can be opened with Windows default browser successfully.

feat(esupports.hop): support `os_open_link` for WSL

---

lua/neorg/modules/core/esupports/metagen/module.lua

So they show up in the wiki.
Here in the [wiki](https://github.com/nvim-neorg/neorg/wiki/Metagen) for the default implementation in the template it only show the `function()` part:
That it is only saying `function()` is just confusing.
I would like to see the full function definition, so I can copy over the ones that I like and adjust what I don't like in my config:

fix(docgen): inline `esupports.metagen` template function definitions

---

lua/neorg/external/helpers.lua
lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/tangle/module.lua
lua/neorg/modules/core/ui/calendar/module.lua
lua/neorg/modules/core/ui/calendar/views/monthly.lua

`utils.get_filetype` doesn't seem to work in autocmd like `BufWritePre` and `BufWritePost`, which is a real problem if you like to set up auto-tangle.
Fortunatly, neovim 0.8 introduce `vim.filetype.match` that does the same natively without issues.
Since the complexity of `get_filetype` has become trivial, I've deprecated the function.

fix: replace `get_filetype` with `vim.filetype.match`

---

lua/neorg/modules/core/journal/module.lua

Fixes #597.
```
Problem:    Cannot open the journal TOC from outside a norg file.
Solution:   Remove command condition from the 'toc' subcommand.
```
This condition seemed completely arbitrary to me. Is there any reason that it exists that I'm unaware of?

fix(journal): Remove condition from 'toc' subcommand (fixes #597)

---

lua/neorg/modules/core/journal/module.lua

Fixes #780.
```
Problem:    'get_title()' isn't able to retrieve the meta title
correctly, because the journal entry buffer is opened with
an incorrect path.
Solution:   Expand the journal entry path correctly.
```

fix(journal): expand entry path correctly (fixes #780)

---

lua/neorg/modules/core/esupports/metagen/module.lua

The function `get_username` is in `utils`

fix: Update `get_username` call

---

lua/neorg/modules/core/tangle/module.lua

An extention to the idea discussed in #955 .
Add heading text as delimiter as a comment if:
1. There is in-fact a current heading. Headings are optional.
2. Current heading hasn't been used as a delimiter before.
3. `commentstring` is available for the filetype in question.
Otherwise just use a newline.
That last one (3) requires making a temporary scratch buffer to trigger ftplugin, which retrieves `commentstring` for all supported filetypes in vim.

feat: delimit tangled code blocks with headings

---

lua/neorg/modules/core/concealer/module.lua

fixes https://github.com/nvim-neorg/neorg/issues/1007

fix(concealer): tolerate duplicate marks caused by undo during rendering

---

.luarc.json
lua/neorg/modules/core/tangle/module.lua

Same as with heading, but uses the entire Neorg file as a delimiter. In other words, the output file is identical as the source, but "inverted" in that blocks are the content and the rest of the document are comments.
Code is configure to work as expected with mulitple targets.
For estethical reason I chose to keep empty lines empty.

feat: delimit tangle code blocks with file content

---

lua/neorg/modules/core/presenter/module.lua

`module.private` was overriden so `current_page` was `nil` when starting instead of  `1` by default.

fix(presenter): ensure module.private is not overriden

---

lua/neorg/modules/core/concealer/module.lua

It is otherwise [confusing](https://discord.com/channels/834325286664929280/834326555160608769/1148243431345369159) to have everything folded by default.

feat(concealer): add option for opening all folds by default

---

doc/neorg.norg

Hey, new neorg user here, thank you for the very cool plugin!
I couldn't figure out why reverse indentation didn't work until I realized the docs were not up to date :) Hope this saves the headache for anyone else.

doc(neorg): fix min reverse indentation count from 2 to 3

---

lua/neorg/modules/core/esupports/hop/module.lua

Partially resolves https://github.com/nvim-neorg/neorg/issues/1039.
One can now open links by external apps with custom keybinds:
```lua
["core.keybinds"] = {
config = {
hook = function(keybinds)
keybinds.map_event_to_mode("norg", {
n = {
{ keybinds.leader .. "ge", "core.esupports.hop.hop-link", "external", opts = { desc = "Open External Link" } },
},
}, { })
end,
}
},
```

feat(esupports.hop): add open mode for external link target

---

lua/neorg/modules/core/summary/module.lua

hey there :)  
i was just trying to debug the links in the summary module not being generated properly.
the issue is that the links are generated as ones relative to current workspace root
( the format of `:$/path/from/current/workspace:`).
however the actuals paths post gsub remain full paths.
for debugging i modified the module.lua like so: 
``` lua
local norgname = filename:match("(.+)%.norg$") -- strip extension for link destinations
vim.print("looking at file: " .. filename)
if not norgname then
-- NOTE: either here
vim.print("DEBUG: treated it as a non norg file")
norgname = filename
end
-- NOTE: or here
norgname = norgname:gsub("^" .. ws_root, "")
vim.print("post gsub: " .. norgname )
```
and that gave me this:
```
looking at file: /home/cherry-cat/Notes/General/index.norg
post …
```

fix(summary): escape ws_root special characters

---

lua/neorg/modules/core/summary/module.lua

uhh yeah i forgor to remove the escaped_ws_root var after @TerryQuiet recommended to switch to the string.len way.

style(summary): drop unused var escaped_ws_root

---

doc/neorg.norg

Following the discussion [here](https://github.com/nvim-neorg/tree-sitter-norg/issues/56), I have added documentation about the `|` character to `neorg.norg`'s basic markup documentation. This introduces users to one of the markup characters available to them, without having to dive into the cheatsheet fully. Additionally, using the `|` character for LaTeX-typeset inline math has now been added to the "*** Math" section. I also added a link to the cheatsheet so users can see a more detailed example there.

docs: add pipe character (`|`) to `:h neorg`

---

lua/neorg/core/utils.lua
lua/neorg/modules/core/concealer/module.lua

The previous version comparison logic seems flawed: (0,10,0) should be greater than (0,7,1), not less.
To ensure that anticonceal is available, it's [not enough](https://github.com/nvim-neorg/neorg/issues/292#issuecomment-1646543885) to only check version being 0.10.0. We must also ensure that the subversion (the number after '-') is greater than 575 or something iirc.

fix(concealer): more precise anticonceal feature detection

---

doc/neorg.norg

Just a quick documentation change to make the link on line 148 of the `:help neorg` doc point to the correct line.
Side note: I made an issue (#1091) before this PR. For future small changes like this one, should I make both the issue and PR or just the PR? Thanks!

fix(`:h neorg`): make link point to correct line in specs

---

queries/norg/highlights.scm

Fixes https://github.com/nvim-neorg/neorg/issues/642
Not sure why but this was fixed with https://github.com/nvim-neorg/neorg/pull/643 and then disappeared a while ago.
Please don't break it again :pray:

fix: `folke/todo-comments.nvim` comments highlighting (again)

---

lua/neorg/modules/core/queries/native/module.lua

When I entered presenter mode in Neorg, I would receive a deprecation warning about `vim.treesitter.query.get_node_text`,
along with a suggestion to replace it with `vim.treesitter.get_node_text`. This PR does exactly that and only that.

fix: don't use deprecated `query.get_node_text()` call

---

lua/neorg/core/modules.lua

Copy/paste error from https://github.com/nvim-neorg/neorg/pull/1001 :smile:.

chore: remove typo from `modules.create` documentation

---

lua/neorg/core/utils.lua
lua/neorg/modules/core/promo/module.lua
lua/neorg/modules/core/qol/todo_items/module.lua

A dotrepeat wrapper for event handlers is implemented in neorg.utils.
As showcases, promo and task event handlers are wrapped, so for example `>>` and `<C-Space>` can now be dot-repeated.

feat: support dotrepeat for `promo` and `todo_items`

---

lua/neorg/core/utils.lua

This fixes a cursor misplacement problem caused by calling `vim.normal()` under insert mode.
For example, pressing `<ctrl-T>` at `* |` where `|` is the cursor will result in `**| ` currently, instead of `** |` as expected.

fix(utils): don't dotrepeat insert mode actions

---

lua/neorg/modules/core/keybinds/module.lua

docs: add an example illustrating how to unmap a keybind containing leader

---

lua/neorg/modules/core/dirman/module.lua

When using the `:Neorg index` command inside the `default` workspace, it is hardcoded to abort without doing anything.
This was introduced in this commit: https://github.com/nvim-neorg/neorg/commit/c60747fcc567d7eb50b16c2007bcfd3a81a934d1, where I believe the intention was to not accidentally create an index file when you forgot to set the workspace.
Besides, I do not think the error message is easy to understand.
However, I do want to take repository-specific notes saved right inside that directory and I need this feature.
So, to make both working I propose to move to index file only-if the file already exists (I believe in this case the command call should be intended) and if the file does not exist, give a detailed error message to the user to show what they should do.
I'd be more than …

Better error message and open index file in default workspace if the file exists.

---

lua/neorg/modules/core/esupports/metagen/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua

Treesitters `for_each_child()` will be deprecated in 0.11. It ias encouraged to use `children()` and implement the recursion yourself.
We use a loop to iterate over the tree's children and call the usual function for each child.
fixes #1104
I am new to lua and this project, so please double check whether this is the behaviour you want. I am not sure if the recursion works.

fix(meta): fix treesitter deprecation warning (#1104)

---

lua/neorg/core/utils.lua
lua/neorg/modules/core/ui/calendar/views/monthly.lua

Living in a non-latin country, life is sometimes hard with neovim.
Unfortunately in lua 5.1, passing Japanese characters `string.len("あいうえお")` does not count the _letters_ but return the byte length which does not fit accurately when the letters are multi-width. The above should be 5 _letters_ but returns 15.
The following screenshot is the result in the calendar ui of `weekday:sub(1, 2)` displaying corrupted weekdays.
As a reference, here's a code you can copy paste to reproduce.
```lua
local weekdays = {
monday = "月曜日",
tuesday = "火曜日",
wednesday = "水曜日",
thursday = "木曜日",
friday = "金曜日",
saturday = "土曜日",
sunday = "日曜日",
}
for en, ja in pairs(weekdays) do
vim.print(en)
vim.print(ja)
for i = 1, string.len(ja) - 1 do
vim.print(ja:sub(i, i + 1)) ---> prints corrupted bytecodes
end …
```

fix(calendar): display weekdays based on `nvim_strwidth`

---

lua/neorg/modules/core/integrations/treesitter/module.lua

While using `Neorg generate-workspace-summary`. I met some problems similar with issue #1108 , and I solved them in this PR
1. `Uncategorized`: Files not opened cannot be categorized. Because `get_document_metadata` function use parser:children() function to get `norg_meta` parser. But closed file's parser contains no children. So I directly use `norg_meta` parser to parse the metadata, if `norg` parser found the metadata tag.
2. `title field ignored`: while parsing metadata with `bufnr`, the first line, like `@ducument.meta` will confuse the treesitter. Then `@document.meta \n title: <some title>` while considered as a whole part. Then title be ignored.
3. `title like '02' be considered as number type`: if title field is like '02', the title node's type will be number, then the value …

fix: workspace summary ignore closed files and title field of metadata tag

---

lua/neorg/modules/core/dirman/utils/module.lua

`core.dirman.utils.expand_path` is the function to resolve filepath with workspace notation (`$<workspace>/`).
This should work with arbitrary file type as it will be used to resolve files in for example `.image $/relative/path/to/image.png`, but currently, it is hardcoded to append `.norg` after the file path.
I've added an argument `raw_path` which, when is true, does not append the norg extension.
The previous calls to this function does not specify this arg, (hence nil) so we should have backwards compatibility.
https://github.com/nvim-neorg/neorg/blob/98f390d8b0c42e40196ea4d831b42b3908137bc3/lua/neorg/modules/core/dirman/utils/module.lua#L45-L47
Not in the scope of this PR but I don't think this works on Windows. I don't have an environment to test Windows so I'll leave it to someone …

fix(dirman): add `raw_path` option to work with arbitrary filetype

---

lua/neorg/modules/core/dirman/module.lua
lua/neorg/modules/core/esupports/metagen/module.lua

This PR closes #1126. I did not want to deprecate any existing functionality so I've made new functions to `write_metadata` with potential new values instead of defaults.
I am unsure if there is still is any need to use `fs_open()` to create the file, now that I instead create a new tab if `no_open` is true. My reasoning for creating a new tab is that in order to `inject_metadata` i need to have a buffer number, so I always open the new file in a new buffer. With tabs i can easily close the new tab without needing to worry about what else was open at the time.
I noticed that there does not seem to be an easy way to add categories into the metadata as it seems the metadata fields need to return a single string.
I thought about added functionality to allow tables of strings as well such …

feat: option to inject specific metadata instead of defaults

---

.github/workflows/.luarc.json
.github/workflows/typecheck.yml

closes #1160
This PR adds a github workflow which verifies the types of all Neorg's code. I expect it to complain quite a lot so the next step will be to clean up all of the type errors it throws :p
Thanks to @pysan3 for the idea!

[FEATURE]: Add typechecking for codebase

---

docgen/docgen.lua
lua/neorg/core/config.lua
lua/neorg/core/lib.lua
lua/neorg/core/log.lua
lua/neorg/core/modules.lua
lua/neorg/core/utils.lua
lua/neorg/modules/core/clipboard/module.lua
lua/neorg/modules/core/completion/module.lua
lua/neorg/modules/core/concealer/module.lua
lua/neorg/modules/core/dirman/module.lua
lua/neorg/modules/core/esupports/hop/module.lua
lua/neorg/modules/core/esupports/indent/module.lua
lua/neorg/modules/core/esupports/metagen/module.lua
lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/fs/module.lua
lua/neorg/modules/core/highlights/module.lua
lua/neorg/modules/core/integrations/nvim-cmp/module.lua
lua/neorg/modules/core/integrations/nvim-compe/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/journal/module.lua
lua/neorg/modules/core/keybinds/module.lua
lua/neorg/modules/core/neorgcmd/module.lua
lua/neorg/modules/core/qol/todo_items/module.lua
lua/neorg/modules/core/queries/native/module.lua
lua/neorg/modules/core/syntax/module.lua
lua/neorg/modules/core/tangle/module.lua
lua/neorg/modules/core/tempus/module.lua
lua/neorg/modules/core/ui/module.lua
lua/neorg/modules/core/ui/selection_popup.lua
lua/neorg/modules/core/upgrade/module.lua

- TODO: This should be dealt with later and eliminate the TODOs <2023-11-15, pysan3 pysan3@gmail.com>

refactor(luacheck): workaround lua type check

---

lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/keybinds/keybinds.lua

A New mode for quick link traversal using "j" and "k" in that mode.

feat: add `traverse-link` Neorg mode

---

lua/neorg/modules/core/journal/module.lua

Fixes a bug in the generated journal ToC where months can only be incremented, resulting in journal entries over multiple years missing months
Also adds some simple indentation to the links so dont they look bad

fix(journal): toc reset month & add link indent

---

lua/neorg/modules/core/clipboard/module.lua
lua/neorg/modules/core/esupports/hop/module.lua
lua/neorg/modules/core/tempus/module.lua
lua/neorg/modules/core/ui/calendar/views/monthly.lua
lua/neorg/modules/core/ui/module.lua
lua/neorg/modules/core/ui/selection_popup.lua

This PR modernizes the old Neovim 0.5 code for the beloved selection popup system that Neorg uses (that's the thing you see when your link is broken!). This is a breaking change as any external module using this UI element now has to update their `:listener` and `:locallistener` calls to excludethe first parameter.

ref(selection_popup)!: modernize code of selection popup

---

lua/neorg/modules/core/journal/module.lua

The action `luacheck` fails from https://github.com/nvim-neorg/neorg/pull/1165, with _value assigned to variable current_quarter is unused_ as you can see [here](https://github.com/nvim-neorg/neorg/actions/runs/6881253495/job/18717231193).
This PR fixes that.
Basically, `current_quater` is substituted with `[1-4]` right after (if-else covers all cases), so there's no reason to put it to `nil` here.
In the action I mentioned above, there's also another error in `core.latex.render` so I asked @nolbap to fix it here: https://github.com/nvim-neorg/neorg/pull/1133#issuecomment-1817793348.

fix(journal): value assigned to variable current_quarter is unused

---

lua/neorg/modules/core/latex/renderer/module.lua

As requested by @pysan3 in https://github.com/nvim-neorg/neorg/pull/1133#issuecomment-1817793348 this PR fixes the `luacheck` errors by creating and calling `module.private` variables instead of global variables.

fix(luacheck): setting non-standard global variables in latex renderer module

---

lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/keybinds/module.lua
lua/neorg/modules/core/tangle/module.lua
lua/neorg/modules/core/upgrade/module.lua

As title.
It seems that stylua automatically reformats the code and the comment are moved so that it doesn't get aligned with the actual problem.
Would you add type checking action to run after the stylua actions as well?
I guess you need to create a separate `GITHUB_TOKEN` for that as I mentioned here: https://github.com/vhyrro/sample-luarocks-plugin/issues/1.
Anyways, this PR changes the places of `---@diagnostic disable-line` so that the langserver is happy again :)

fix(luacheck): fix type errors caused by autoformat

---

lua/neorg/core/modules.lua

If a module `wants` another module, the loading process checks `config.user_config` for that module configuration. However, module configs are located in `config.user_config.load`.

fix(modules): Check the right config key in module.wants

---

lua/neorg/modules/core/concealer/module.lua

Horizontal rules can now start from the very left of window (`left="window"`) or from the node position (`left="here"`), and end at the very right of window (`right="window"`) or at the column of `textwidth` defaulted to 79 just like vim (`right="textwidth"`).

feat(concealer): add configuration for hrule start and end position

---

lua/neorg/modules/core/qol/toc/module.lua

Currently all nodes whose type ends with `_prefix` are extracted into the ToC window, including footnotes, whose node type is `single_footnote_prefix`.
This PR adds a customizable filter function for ToC items, which only allows headings into the ToC by default.

feat(toc): add toc item filter

---

lua/neorg/modules/core/qol/toc/module.lua

Title should be cleared when encountering new prefix, otherwise for docs like:
```norg
^ footnote-title
text
* heading-text
```
the toc would be `* footnote-title`.

fix(toc): clear title after assigning prefix

---

lua/neorg/modules/core/qol/toc/module.lua

New boolean option: `sync_cursorline`.
When enabled:
- `cursorline` is enabled (highlighted) in the ToC window
- when the cursor of the content window changes, the cursor of the ToC window changes accordingly
So that one can track which section they're reading in the ToC window.

feat(toc): add config for enabling synchronized cursorline in toc window

---

README.md

This PR clarifies font requirements in the README. Please see this discussion: https://github.com/nvim-neorg/neorg/discussions/1243.

docs(README): clarify font requirements in the README

---

lua/neorg/modules/core/qol/toc/module.lua

1. Sync cursor upon creating toc (resolves https://github.com/nvim-neorg/neorg/pull/1198#issuecomment-1836332823)
2. When previewing from toc, keep the previewed heading in screen center (like `scrolloff=999`)
3. enable folding so that one can `zc` and `zo` on toc items
4. ToC per tabpage instead of per nvim session
5. display todo status (resolves https://github.com/nvim-neorg/neorg/issues/1237)
6. `:Neorg toc` updates ToC instead of throwing errors when ToC exists

feat(toc): improve toc

---

lua/neorg/core/modules.lua
lua/neorg/modules/core/autocommands/module.lua

Fixes https://github.com/nvim-neorg/neorg/issues/1188.
It turns out that the problem is not from concealer but from the event system: when for example scrolling a window that does not have the focus, it would be wrong to assign the "current" buffer id to the event.

fix(autocommands): pass correct buffer id

---

lua/neorg/modules/core/upgrade/module.lua

Fixes #1206 
The purpose is to ensure that `neorgcmd` can launch the ui selector when the user doesn't provide the necessary arguments to the `upgrade` module.
At `/neorg/lua/neorg/modules/core/neorgcmd/module.lua:258`, a check is performed to ensure that at least the minimum number of arguments have been provided for the given module. The core module `upgrade` currently does not set this `min_args` property at all, resulting in an error when attempting to call `:Neorg upgrade`. By communicating that `upgrade` requires at least 1 arg, `neorgcmd` will be able to call the function `select_next_cmd_arg` at line 260.

fix: record that module `upgrade` requires at least 1 arg

---

.github/workflows/lint.yml

[`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) runs against the **target** branch (`neorg/main`) and not the content of the PR head.
Therefore, action results in [this PR](https://github.com/nvim-neorg/neorg/pull/1198) succeeds even tho the actual PR content is [messed up](https://github.com/nvim-neorg/neorg/actions/runs/7059860778/job/19218279880).

fix(action): run lint action against pr head

---

lua/neorg/modules/core/keybinds/keybinds.lua

closes #1113 
Prefix was not capitalized to be bit more searchable (in case users use case-sensitive search)
---
Command used to to generate the change:
```
sed -i 's/desc = "/desc = "[neorg] /' lua/neorg/modules/core/keybinds/keybinds.lua
stylua lua/neorg/modules/core/keybinds/keybinds.lua
```

feat: prefix all keybind descriptions with "neorg" for discoverability

---

lua/neorg/modules/core/esupports/hop/module.lua

Fixes an error when hopping a link across lines:
```norg
{/ /link/target}[description
across
lines]
```

fix(hop): fix range check across lines

---

lua/neorg/modules/core/esupports/metagen/module.lua

fixes #1233
no way I got #1234

fix: `update-metadata` would fail to work with several parse trees in the document

---

lua/neorg/core/lib.lua
lua/neorg/modules/core/summary/module.lua

I like to organize my .norg files in subfolders and I'd like to use the names of these subfolders as the category for the files contained in them. With this change the command `generate-workspace-summary` can make use of this information.

Add a new strategy `by_path` for summary generation

---

lua/neorg/modules/core/qol/toc/module.lua

This feature already existed weeks ago but I somehow dropped it by mistake in the recent PR.

feat(toc): don't scroll content window when switching to toc

---

README.md

I've added:
1. Lazy loading on file type.
2. The "tag" thingy.

docs(README): improve lazy.nvim installation instructions

---

lua/neorg/modules/core/tangle/module.lua

> Do we need this warning? https://github.com/nvim-neorg/neorg/blob/aa8e66dd40c07a4de58f9ed93f27ab4dac9a241c/lua/neorg/modules/core/tangle/module.lua#L424
> I run an autocmd for all norg files to automatically try tangling, and I don't want to get a warning everytime.
>
> @pysan3
- Add `report_on_empty` option.
```lua
module.config.public = {
-- Notify when there is nothing to tangle (INFO) or when the content is empty (WARN).
report_on_empty = true,
}
```
- Fixes some type errors from https://github.com/nvim-neorg/neorg/pull/1162
- I'm not sure how to update the wiki: https://github.com/nvim-neorg/neorg/wiki/Tangling
- I'd be happy if you could guide me how.
- Possibly conflicts with https://github.com/nvim-neorg/neorg/pull/1167

feat(tangle): add `report_on_empty` option in `core.tangle`

---

lua/neorg/modules/core/concealer/module.lua

`vim.treesitter.foldexpr()` behaves more stably than `nvim_treesitter#foldexpr()`

fix(concealer): use vim.treesitter.foldexpr for stabler folding

---

lua/neorg.lua
lua/neorg/core/callbacks.lua
lua/neorg/core/config.lua
lua/neorg/core/lib.lua
lua/neorg/core/log.lua
lua/neorg/core/modules.lua
lua/neorg/core/utils.lua

This PR adds LuaCATS annotations (i.e. the annotation standard used by the lua language server) to the core of Neorg (not to all modules, but just to the core).
LuaCATS is a more modern spinoff of EmmyLua.
This gives proper type checking, better autocompletion and verifying the contents of tables provided to the `setup()` function. It's even useful to users as they can have autocompletion for their config :D

[Lua]: Add annotations to the core codebase.

---

lua/neorg/modules/core/export/markdown/module.lua

fixes #720, along with markdown embeds not being exported (unless they were the first tag in the file), the first tag on a file always being exported by default, and adds support to export latex `embed` tags (disabled by default through an extension)

fix(export.markdown): fix export of `embed` tags

---

lua/neorg/modules/core/keybinds/module.lua

For consistency with the `map` keybind hook. (#1255)
The new `opts` table has priority over the old one. Feel free to reject the PR if not allowing to override `opts` is intentional.

feat(keybinds): add `opts` arg to `remap(_event)`

---

.github/workflows/.luarc.json

> Yeah I tried to fix it by pinning to the latest version but it's still failing for some reason :thinking: 
>
> It's unable to find the neodev files, despite them being there (I've been debugging the CI for the best part of half an hour now :/)
>
> _Originally posted by @vhyrro in https://github.com/nvim-neorg/neorg/issues/1265#issuecomment-1879760949_

fix(ci): fix abs path to libs in luarc

---

lua/neorg/modules/core/export/markdown/module.lua

fix(export.markdown): fix error on unexported verbatim tags without parameters

---

lua/neorg/modules/core/completion/module.lua
lua/neorg/modules/core/integrations/nvim-cmp/module.lua

Adds auto completion for links to the completion module.
closes #752 
https://github.com/nvim-neorg/neorg/assets/56943754/69e7fb8e-1055-49a5-bc3a-41517f842036
Here's a list of the completions:
- `{:|}` workspace relative file paths
- `{#|}` all headings in the current file
- `{*|}` level 1 headings in current file (TODO status is removed)
- `{**|}` level 2 headings in current file (and so on)
- `{^|}` footnotes in the current file
- `{:path:#}` headings from the file at path
- `{:path:*}` level n headings from the file at path
- `{:path:^}` footnotes from the file at path. Will find `^ footnote` and `^^ long footnote`
All of these should work with spaces after the item (ie. `{# |}` will still complete correctly).
All of them should close the link correctly if it's not closed (ie. …

feat: auto complete links

---

lua/neorg/modules/core/integrations/nvim-cmp/module.lua

Fixed problem with sources being enabled on buffers with file types other than `norg`

fix: enable source of `nvim-cmp` only norg file type

---

README.md

Because some lazy.nvim distributions set lazy=true by default, I add some config to make the plugin load correctly. (and add a lazy load config when I am in there too)

docs(README.md) clarify lazy load in lazy.nvim snippet

---

lua/neorg/modules/core/highlights/module.lua

Matches the new names in https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0
This is a breaking change for users whose colorscheme hasn't been updated yet to follow this change

fix(highlights)!: updated default groups to match names in treesitter

---

lua/neorg/modules/core/syntax/module.lua

Workaround [this](https://github.com/nvim-neorg/neorg/actions/runs/7438125419/job/20236558645).

fix(syntax): ignore type annotation errors in syntax module

---

lua/neorg/modules/core/concealer/module.lua

Numeric footnote links are superscripted, but the ones mixed with non-digits (like  `{^ abc123456abc}`) were mistakenly superscripted (to a mess) as well. This PR fixes the issue.
Dash (`-` ) is now also supported.

fix(concealer): footnote pattern should be matched against full string

---

README.md

Otherwise the tl;dr instruction fails due to https://github.com/nvim-neorg/neorg/commit/56ad8056b6180dba60ddbd5bca2f29de12f3bd1d.

doc: pin version to v7.0.0 in tldr

---

lua/neorg/modules/core/esupports/metagen/module.lua

addresses issues brought up in #1112 (currently closed)
Updating the time stamp can cause issues with undo-ing things. This is particularly bad when an autosave plugin is used b/c the user will make a change > autosave > timestamp update > autosave > undo (undoes timestamp update) > autosave > timestamp update > loop. The scenario's described assume there is an autosave plugin saving on text change/insert leave.
Making it impossible to undo changes in the norg file with autosave (while the `updated:` field is present in the metadata).
This PR makes two changes that make it possible to bind keys to mitigate this issue:
- `["core.esupports.metagen"].config.undojoin_updates = true` - When true, we call `:undojoin` just before updating the `updated:` field in the metadata. With this set to …

feat: undojoin timestamp updates

---

lua/neorg/modules/core/concealer/module.lua

closes #1327
_It doesn't quite do what that issue says, but I like this better._
Lets you set a min width for code cell background highlights. It's also an incredibly simple change.
New configuration looks like this:
```lua
-- ...
["core.concealer"] = {
config = {
icons = {
code_block = {
width = "content",
min_width = 85,
},
},
},
},
-- ...
```
And the result:

feat(concealer): code block background `min_width`

---

lua/neorg/modules/core/concealer/module.lua

This should fix the problem described in #1121. Maybe with the latest greatest nvim this problem is also bypassed (see 086891d). But the fix is still relevant for older nvim versions.
The problem seems to be that lua `line:sub` method is not Unicode-aware and does not work properly with strings that contain Unicode characters. That is definitely the case when concealer required more than one substitution (one for heading, one for todo marks). First substitution (heading) would work fine, but the second one (todo mark) would become off.

Fix for issue #1121

---

lua/neorg/core/modules.lua

When I open a `.norg` file from a command and the current buffer is not a file or an editable buffer,
such as the `neo-tree` buffer it throws this error:
```
Error executing Lua callback: vim/_editor.lua:0: nvim_exec2()..BufEnter Autocommands for "*.norg": Vim(append):Error executing lua callback: .../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:759: Invalid window id: -1
stack traceback:
[C]: in function 'nvim_win_get_cursor'
.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:759: in function 'create_event'
...azy/neorg/lua/neorg/modules/core/autocommands/module.lua:49: in function '_neorg_module_autocommand_triggered'
...azy/neorg/lua/neorg/modules/core/autocommands/module.lua:84: in function <...azy/neorg/lua/neorg/modules/core/autocommands/module.lua:83>
[C]: in …
```

Fix for error Invalid window id: -1

---

lua/neorg/modules/core/esupports/metagen/module.lua

Add a capability to override system username that is used in generated metadata.
```
{
["core.esupports.metagen"] = {
config = {
author = "Vladimir Gusev",
},
},
}
```
```
authors: Vladimir Gusev
```

feat: add author field to provide custom author name in config

---

lua/neorg/modules/core/export/markdown/module.lua

When pandoc reads the metadata block of a markdown file, it uses the `author` field to set the authors' names. Neorg, however, uses the `authors` field for this. This patch converts the key name during export so the data can be properly recognized on both cases

fix(export.markdown): export `authors` metadata field key as `author`

---

lua/neorg/modules/core/export/markdown/module.lua

Previous implementation resseted the counts of the higher levels when a lower level node was processed. This resulted in them not being resseted when a list was broken without an ordered list of a lower level

fix(export.markdown): fix incorrect reset of ordered list item count

---

lua/neorg/modules/core/esupports/metagen/module.lua

I added `undojoin_updates` to the metagen module in #1272 to create a better experience for autosave users, and then didn't document it in the wiki, only in the PR. So here's an update to the documentation to make that more clear.

docs: undojoin_updates/autosave instructions

---

.github/workflows/.luarc.json
.github/workflows/typecheck.yml
lua/neorg/core/utils.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/tempus/module.lua

This conflicts with this PR so I'll update it later.
- https://github.com/nvim-neorg/neorg/pull/1354

fix(typecheck): use type definitions from nvim runtime instead

---

lua/neorg/modules/core/defaults/module.lua
lua/neorg/modules/core/todo-introspector/module.lua

The old introspector code was forgotten over a year ago, so time to revive it!
The introspector is the handy module which displays `[0/1] (0%)` next to things that have subtasks.
TODOs:
Everything else is fully functional already :)

TODO Introspector version 2 electric boogaloo

---

.github/workflows/.luarc.json
.github/workflows/luarocks.yml
.github/workflows/typecheck.yml
.gitignore
.luarc.json
build.lua
lua/neorg/core/modules.lua
lua/neorg/core/utils.lua
lua/neorg/modules/core/completion/module.lua
lua/neorg/modules/core/dirman/module.lua
lua/neorg/modules/core/dirman/utils/module.lua
lua/neorg/modules/core/esupports/indent/module.lua
lua/neorg/modules/core/integrations/nvim-cmp/module.lua
lua/neorg/modules/core/integrations/nvim-compe/module.lua
lua/neorg/modules/core/latex/renderer/module.lua
lua/neorg/modules/core/promo/module.lua
lua/neorg/modules/core/summary/module.lua
lua/neorg/modules/core/tempus/module.lua
lua/neorg/modules/core/ui/calendar/module.lua
neorg-scm-1.rockspec

[pathlib.nvim](https://pysan3.github.io/pathlib.nvim/README.html) is a plugin which aims to decrease the difficulties of path management across mutliple OSs in neovim. The plugin API is heavily inspired by Python’s pathlib.path with tweaks to fit neovim usage.
You can search through the methods at: https://pysan3.github.io/pathlib.nvim/search.html
This adds pathlib.nvim to neorg's dependencies managed by `.github/workflows/luarocks.yml` and `build.lua`.
This commit also changes the typecheck CI to install all its dependencies defined by `*.rockspec` and use the packages for type annotations. Thanks to this change, types like `PathlibPath` (defined in pathlib.nvim) also get annotated as a valid type and will be type-checked against.
You will want to do this with local development as well. …

feat(dirman)!: use pathlib for all dirman operations 

---

.github/workflows/luarocks.yml
build.lua
lua/neorg/modules/core/dirman/module.lua
neorg-scm-1.rockspec

I noticed that I ignored the `opts.force` flag in `dirman.create_file`.
Now respects `opts.force` to decide whether to create a new empty file, or, append to the file  to just update the timestamp.
I also had a bug in pathlib `self:touch` so I changed to use `fs_open` instead.
This is fixed in `pathlib.nvim ~> 2.2` so bumped the version as well just in case.
Fixes: https://github.com/nvim-neorg/neorg/issues/1365

fix(dirman): respect force option in dirman create_file

---

lua/neorg/health.lua

Added the missing `key` to `string.format` when logging a warning about attempting to load an unknown module.

Add missing parameter to string format.

---

README.md

The links on the main page are broken.
I edited them so that they again mirror the page's structure. I placed the line break so that the layout looks similar to before. I kept the roadmap link as it was. I suppose it is still intended to be there?

docs(README): Fix navigation links

---

README.md

Documentation (readme) update to make the install instructions for luarocks.nvim more clear.
- links the repo (b/c it very hard to find by nature of it being a fork)
- make it more clear that `luarocks.nvim` has additional installation steps
_also, I haven't done it in this PR, but I think that we should add Pysan's written tutorial to the README._

docs: emphasise luarock.nvim extra install steps

---

ROADMAP.md
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/text-objects/module.lua

The rebirth of the manoeuvre module, and the death of that awful (to spell) name.
- Rips the `swap_node` function from `nivm-treesitter/nvim-treesitter`'s `ts_utils` and fixes the way it handles trailing blank lines
- Changed text object names to be more normal (ie. `around-heading` -> `heading.outer`)
- update the roadmap to reflect that this work is done
---
~~Text object ranges are kinda bad right now. They select onto the line of the next heading.. probably just an off by one, I'll correct that.~~
This might be fine the way it is. it's just including the last newline in the selection, I think that it looks weird, but it's not he end of the world. Would want to see your thoughts.

feat: text-objects and working swap

---

res/wiki/static/Dependencies.md

was missing the terminal character `m` in ANSI color code for color red.

docs(dependencies): fix typo on red ANSI color code

---

res/wiki/static/Kickstart.md

had a lot of issues with neorg on alpine till @vhyrro helped discover an upstream gnu wget dependency. I tested with builds.sr.ht to ensure those dependencies would be enough with the kickstart config:
https://builds.sr.ht/~acsqdotme/job/1223933

docs(wiki/kickstart): add alpine requirements

---

lua/neorg/modules/core/highlights/module.lua
lua/neorg/modules/core/integrations/image/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/latex/renderer/module.lua

https://github.com/nvim-neorg/neorg/assets/56943754/d5f8e015-2cb3-4497-985d-ab9dca7f761a
Brings many many improvements to the latex renderer:
- Images are created and show asynchronously using nvim-nio
- Creating images never blocks nvim, even with excessive amounts of images
- Images correctly position themselves in line (accounting for other virtual text, folds, etc.)
- Enable/Disable commands
- minimum length requirement to render. This allows you to type `$x$` and not have it render a massive disproportionate letter `x` for no good reason
- Better documentation
- Image caching
- Persistent images with auto update--before images would just disappear when you started typing
- Foreground color controlled by a highlight group
- this updates and rerenders on colorscheme change
- Default …

feat(latex): async image rendering

---

lua/neorg/modules/core/esupports/hop/module.lua
lua/neorg/modules/core/links/module.lua

Pulls out a link query from esupports.hop into a `core.links` module, which only exists to house that one query at the moment.
The query will be used in the completion module in the TS autocomplete PR.

chore: refactor links query into separate module

---

lua/neorg/modules/core/export/markdown/module.lua

This closes (https://github.com/nvim-neorg/neorg/issues/988).
This is mostly useful for using pandoc to change the markdown file into a pdf so that it can show footnotes.

add footnote to markdown export

---

flake.lock

chore: update lock--avoid broken package on macs

---

lua/neorg/modules/core/latex/renderer/module.lua

Adds another call to yield to the scheduler so that we don't call a vim function when we're not supposed to.
It's only by shear luck that this didn't break on us all the time.
also, this commit was the problem: https://github.com/nvim-neorg/neorg/commit/2a9c3fab1bb6beabc4160264835be7f3b9a579e7

fix(latex-renderer): handle broken latex

---

lua/neorg/modules/core/text-objects/module.lua

Attempting to swap with the root element threw an error b/c it doesn't have a parent, and we weren't nil checking it.

fix(text-objects): nil check node's parent

---

lua/neorg/modules/core/dirman/module.lua

Fixes a bug brought up by a discord user where calling `:Neorg index` when the index file had a swap file available would trigger a loud and confusing error.
Now `pcall`ing the source of the error, and issuing a nicer warning instead.

fix: swapfile bug

---

lua/neorg/modules/core/completion/module.lua
lua/neorg/modules/core/integrations/coq_nvim/module.lua
lua/neorg/modules/core/integrations/nvim-cmp/module.lua
lua/neorg/modules/core/integrations/nvim-compe/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua

Adds:
- Link names completions for links like:
- `{:$/some/file:# Heading}[|` - suggests file title, file description, and "Heading"
- `{:$/some/file:}[|` - suggests file title and description
- and `{** local heading}[|` - suggests "local heading"
- Anchor completions (`[|`) with `[a1]{# something}` in the document will suggest "a1"
- additional detached modifier extensions for: `$`, `^`, `*`, and `~`
Refactors so TS helpers to take more sources, I'm slowly unifying the Neorg TS functions so they can all take buffer numbers, file paths, source strings, or nil for current buffer.
Fixes an off by one in get node text when the source was a string.
---
I think this wraps up all the completions. If there are more that I'm missing, let me know, but  I can't think of any new ones.. ~~Maybe it …

More completions

---

lua/neorg/modules/core/concealer/module.lua

fixes #1447 for nvim 0.10+ users

fix(concealer): invalidate extmarks when range is deleted

---

lua/neorg/modules/core/dirman/module.lua
lua/neorg/modules/core/dirman/utils/module.lua
lua/neorg/modules/core/esupports/hop/module.lua

#1451 caught an error caused by swap files and produced an error message that heavily suggested the error was caused by swap and could be ignored when that was never confirmed. Some concern was raised about this approach, and an additional cases of the same bug was found...
So this PR checks the error message (via pattern match) to confirm that a swap error was the cause of `vim.cmd.edit` failing, and in these cases eats the error message. It's okay (and I'd say preferred) to eat this error b/c a lengthy swap message will pop up on screen for the user, so users will not be confused about what's happening.
In case the error is not caused be swap, it's now re-raised with the exact error message.
#1451 handled the edit call in `:Neorg index`, this pr additionally handles a call in the hop …

fix: supress swap file errors

---

lua/neorg/modules/core/latex/renderer/module.lua

Commit [8ec38e0](https://github.com/nvim-neorg/neorg/commit/8ec38e07ddffa84d0925faf425d4d52e5c1f91b7) changed the implementation of the treesitter module's `execute_query` function. The function asks for a non-nil source, but the latex renderer wasn't providing one (which should have caused a type error, but didn't because the way the `module.required` table works prevents lua_ls from getting the function's signature). The previous implementation happened to use a function internally that used the buffer 0 when `source` was omitted to get the parser, which is what allowed the latex renderer to work previously, but the new implementation didn't do that

fix(latex-renderer): fixed renderer failing silently

---

lua/neorg/modules/core/latex/renderer/module.lua

Previously, when a snippet that had already been rendered was modified and the new version failed to compile, the renderer got stuck on a bad state until that snippet was fixed: the rendered image of other snippets wasn't updated when they were modified, and the last rendered image of the bad snippet would keep being shown. Additionally, if by the time the bad snippet was fixed any other snippets were different from before the bad snippet stopped compiling, those snippets would get re-rendered and their previous image would get stuck on the screen.
This patch fixes this issue: now when a snippet is modified and it stops compiling its rendered image is properly cleared and the rest of the snippets are unaffected.
Before:
https://github.com/nvim-neorg/neorg/assets/43814863/10aa2c5f-040b-4f34 …

fix(latex-renderer): fixed renderer breaking when a snippet change made it stop compiling

---

lua/neorg/modules/core/esupports/hop/module.lua

This PR lets the user know that wiki links are unsupported instead of erroring out with a "link not found message".

fix(hop): describe which links are currently unsupported instead of "not found"

---

lua/neorg/modules/core/latex/renderer/module.lua

Adds a new `:Neorg render-latex toggle` command that simply enables the renderer if it was off and disables it if it was on. A user couldn't do this themselves because the renderer enabled state was private
https://github.com/nvim-neorg/neorg/assets/43814863/90fa28a9-a207-417a-8a91-21edc5b78fde

feat(latex-renderer): add toggle renderer command

---

lua/neorg/modules/core/esupports/metagen/module.lua

Hi, I am new to neovim plugin development and this is my first PR.
I've introduced a check to verify if your buffer has been modified before updating the date in the metadata module. This prevents accidentally updating the last modified date when closing vim with :wq or ZZ even when no changes have been made.

Don't update metadata unless buffer is modified

---

lua/neorg/modules/core/integrations/truezen/module.lua

Updates the module to reflect the true-zen folder structure. As pointed out by `TwoNine` on neorg [discord](https://canary.discord.com/channels/834325286664929280/1254590615279112202/1254599573989490739)
Prevents error on startup 
```                                                                                                                    
Recovering from error...                                                                                                                                                                       
Press ENTER or type command to continue
```

small true-zen integration folder structure fix

---

lua/neorg/modules/core/completion/module.lua
lua/neorg/modules/core/qol/toc/module.lua
lua/neorg/modules/core/todo-introspector/module.lua
lua/neorg/modules/core/ui/module.lua

closes #1475 
- configurable max width
- automatically open/enter ToC on neorg buf enter
- close ToC when norg buffer is closed
- exit nvim when ToC is the last window (similar to how help windows function)
- set `winfixbuf` on the ToC window
These are all configurable behaviors.
- when a ToC is open and it's norg buffer has been removed, it will no longer throw an error when you try to jump to a heading, instead it opens a new buffer, re-sets the ToC width, and placed your cursor in the right spot.
- opening a ToC from within a ToC window will no longer break the window
---
There's also a random completion documentation fix in here b/c I'm lazy and don't want to open a separate PR.

More ToC QoL features/fixes

---

lua/neorg/modules/core/journal/module.lua

I noticed this small bug as I've begun using journal entries in my notes.
I believe the problem occurs because I've set metagen.type = "auto".
This fixes a bug where metadata is injected into the newly created file before the template contents. Which results in the template content being placed above the metadata.
By changing the 0 to a $ we always insert the template at the end of the file. I believe this is safe as this only occurs on newly created journal entries, which should therefore always be empty (except for some possible metadata injected by metagen).

fix: insert template at the end of a new note

---

lua/neorg/modules/core/ui/calendar/views/monthly.lua

closes #1340 
Notably, the suggested `g` in that is now `d` and the suggested `t/T` is now `g/G` b/c `t` is already taken.

More calendar UI mappings

---

lua/neorg/modules/core/summary/module.lua

Current state sometimes mixes entries with nested categories. For example, if there is three items:
- C with category cat
- A with category cat.sub
- B with category cat.sub
The produced summary looks like this:
```
* Index
** Cat
*** Sub
- A
- B
- C
```
even though I want C to be directly under `Cat`. With multiple notes this causes nested categories to be rather messy sometimes.
I fixed this by simply introducing few temporary variables and adding nested categories to the summary at the end.

fix(summary): ordering and indentation of nested entries

---

lua/neorg/modules/core/esupports/indent/module.lua
lua/neorg/modules/core/keybinds/keybinds.lua
lua/neorg/modules/core/promo/module.lua

what it says on the tin. These were broken/removed a while ago. Presumably due to concealer changes but I'm not sure. Someone asked about bringing them back today, so here they are.
The re-indentation code in this module seems to struggle a little though. Not sure what's up with that.

fix(promo): promote/demote range + keybinds

---

ftdetect/norg.lua

This PR aims to remove `vim.filetype` logic in setup as it is already covered by the ftdetect file.
FYI: ftdetect directory is going to be deleted once Neovim v0.10 release is stable as I've added support for norg filetype in Neovim's core.

cleanup: remove `ftdetect` file as Neorg is now natively recognized by Neovim

---

README.md
lua/neorg/init.lua

stacked on #1506
This PR bumps the required version of Neovim for Neorg. This allows users to access:
- The calendar
- Date-related utilities
- Native filetype detection for .norg files

refactor!: make Neovim 0.10 a requirement for Neorg

---

neorg-scm-1.rockspec

I found #1083 forgot to delete the `ftdetect` from the rockspec.
This gives error when I try to install neorg with luarocks.
```
$ luarocks --force-lock --lua-version=5.1 --dev install neorg
Installing https://luarocks.org/dev/neorg-dev-1.rockspec
Cloning into 'neorg'...
remote: Enumerating objects: 29624, done.
remote: Counting objects: 100% (1687/1687), done.
remote: Compressing objects: 100% (631/631), done.
remote: Total 29624 (delta 806), reused 1413 (delta 626), pack-reused 27937
Receiving objects: 100% (29624/29624), 4.68 MiB | 16.54 MiB/s, done.
Resolving deltas: 100% (15183/15183), done.
Missing dependencies for neorg dev-1:
nvim-nio ~> 1.7 (not installed)
lua-utils.nvim 1.0.2 (not installed)
neorg dev-1 depends on lua >= 5.1, < 5.4 (5.1-1 provided by VM: success)
neorg dev-1 …
```

cleanup: remove `ftdetect` from rockspec

---

lua/neorg/health.lua
lua/neorg/modules/core/keybinds/module.lua

This PR introduces three key changes:
- Don't forcefully override the user's keys
- Add proper `:checkhealth` integration which looks for various conflicts and remaps
- Set global keybinds only once, and apply all norg-specific keys on `Filetype` instead of `BufEnter`
All in all, this concludes the major changes I wanted to make to the keybind system. I personally consider the system to be very close to perfect now, just like the Neovim overlords intended.

Disallow keybind clashes

---

lua/neorg/modules/core/integrations/otter/module.lua

[Otter.nvim](https://github.com/jmbuhr/otter.nvim) got a pretty large update.
TL;DR: it's a language server now, so no need to custom keybinds (normal LSP keybinds are used)

feat(intergrations.otter): update to use otter 2.0

---

lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/tangle/module.lua

Adds the `tangle_on_write` option to the tangle module. Defaults to false, when true, call `:Neorg tangle current-file` on `BufWritePost`.
Fixes an annoying "bug" where tangling fails when code is de-dented. This is just a qol thing, I don't see a point in failing with a loud error in this case when we can easily handle the error and correctly export anyway.

feat: auto tangle

---

lua/neorg/modules/core/esupports/metagen/module.lua

Allow things like this:
```lua
["core.esupports.metagen"] = {
config = {
undojoin_updates = true,
type = "empty",
template = {
{ "title" },
{ "description" },
{ "authors", "[\n  benlubas\n  Zlare\n]" },
}
},
},
```
which generates:
```
@document.meta
title: test1
description: 
authors: [
benlubas
Zlare
]
@end
```
This was requested in the discord by `@zlare`

feat: support multi-line values in metagen

---

lua/neorg/modules/core/keybinds/module.lua

Previous implementation was trying to get the keymap opts from the list of keybinds for each mode rather than from the table of each mapping. I guess that was a typo because none of the mode lists have an opts field, but all of the mapping tables do

fix(keybinds): correctly get keymap opts

---

lua/neorg/modules/core/keybinds/module.lua

The command is defined in the tempus module as `neorg.tempus.insert-date.insert-mode`, but the default mapping was using `neorg.tempus.insert-date-insert-mode` and thus not working properly

fix(keybinds): fixed tempus insert date insert mode default keybind command

---

doc/neorg.norg
lua/neorg/modules/core/concealer/module.lua

Please help test this PR before it's merged! This PR adds proper quote concealing to Neorg, by displaying the box chars for every separate line. Example:
```
> This is a quote
and this still belongs to said quote!
```
Previously, the second line would not be highlighted, even though it absolutely should.
This change fundamentally changes some concealer functionality. If you find any concealer bugs that weren't present earlier, please let me know!
@benlubas would you have some time to try and break this thing?

feat: proper quote concealing

---

lua/neorg/modules/core/pivot/module.lua

First pass. Might still need some cleaning up but toggling / inverting sublists is working. I can also write some tests for this, what is the status on testing? Do we have this set up already?
Demo:
https://github.com/nvim-neorg/neorg/assets/4333381/e37dc621-7765-4399-b734-1d79ced0deb2

feat: List toggling/inverting for sublists

---

lua/neorg/core/modules.lua
lua/neorg/modules/core/clipboard/module.lua
lua/neorg/modules/core/export/markdown/module.lua
lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/fs/module.lua
lua/neorg/modules/core/itero/module.lua
lua/neorg/modules/core/journal/module.lua
lua/neorg/modules/core/keybinds/module.lua
lua/neorg/modules/core/latex/renderer/module.lua
lua/neorg/modules/core/looking-glass/module.lua
lua/neorg/modules/core/pivot/module.lua
lua/neorg/modules/core/qol/todo_items/module.lua
lua/neorg/modules/core/summary/module.lua
lua/neorg/modules/core/syntax/module.lua
lua/neorg/modules/core/tangle/module.lua
lua/neorg/modules/core/text-objects/module.lua
lua/neorg/modules/core/ui/calendar/views/monthly/module.lua
lua/neorg/modules/core/ui/selection_popup/module.lua
lua/neorg/modules/core/ui/text_popup/module.lua

Did a quick POC for automatic typing of module resolves. Wondering if something like this would be useful to us. Benefit is that doing `local mod = module.required[{dependency}]` mod will be automatically typed with the correct class and will give us luals type hints and typechecks without having to do something like this every time:
```lua
---@type core.integrations.treesitter
local ts = module.required["core.integrations.treesitter"]
```
Type hinting:
It already showed some incorrectly type methods in the codebase
We also get automatic suggestions on which modules can be imported as you can see below:
Downside is obviously that any new added modules will have to be updated in that new `neorg.module.resolver` class
Thoughts/feedback? @vhyrro @benlubas

Automatically typed module.required dependencies

---

lua/neorg/modules/core/neorgcmd/commands/return/module.lua

`:Neorg return` was bringing you to the first file you opened, this is not what the docs say, and also not intuitive.

fix: Neorg return to most recent file

---

lua/neorg/modules/core/todo-introspector/module.lua

Added documentation and configurability to the todo-introspector. By default should behave as the old one, but you now have the ability to configure:
* The format and highlight group it displays in
* Which tasks are counted towards completed and total tasks
Also closes #1512 in terms of documentation needed

feat(introspector): Todo-introspector improvements

---

lua/neorg/modules/core/qol/toc/module.lua

When switching buffers really quickly with auto TOC enabled, we could enter and leave a norg buffer before the scheduled function gets to run, which results in a noisy error message from Neorg Command saying `:Neorg toc` only works from a norg buffer.

fix(ToC): only try to open when still in norg buffer

---

lua/neorg/modules/core/esupports/metagen/module.lua

Hello, I was setting up a custom metagen template in my config to change how `title` was formatted and found the docs lacking. I think an example configuration for the template would be helpful here, particularly want the docs to mention #1079, is useful and I discovered this behavior by searching issues.

docs: Add template example to metagen docs

---

lua/neorg/core/callbacks.lua
lua/neorg/modules/core/summary/module.lua

fixes documentation of https://github.com/nvim-neorg/neorg/wiki/Summary
by removing a leftover comment

fix comment

---

lua/neorg/modules/core/completion/module.lua

This caused problems with completion engines that didn't do extra work. As a result, completion worked fine with cmp, but caused extra chars to be completed for other engines like builtin, and now care.nvim. (probably mini-completion too but I've never tested).
Now it works with all of them!

fix: don't suggest leading chars for file completions

---

lua/neorg/modules/core/esupports/indent/module.lua

First time contrib here - first time using org mode for takign notes and struggled for ~2 hours trying to figure out indentation. Felt it was necessary to send in a PR so others would have a easier path :) lmk if anything isn't up to par and I'll be more than happy to fix it :smile:

docs: clarify usage of tweaks and indentation in core.esupports.indent

---

lua/neorg/modules/core/concealer/module.lua

This has come up enough times that I feel justified in making this PR even though you intentionally changed it to the x a while ago.

fix: intuitive default undone icon

---

lua/neorg/modules/core/integrations/coq_nvim/module.lua

fix: add coq_nvim completion integration

---

lua/neorg/modules/core/esupports/hop/module.lua
lua/neorg/modules/core/keybinds/module.lua

This adds `:tab drop` as an option for opening a file when clicking a file link. Tab drop as an option would be helpful to avoid opening a file a new tab, when it has already been open somewhere else.
IMO, this could be a replacement for the `tabnew` option itself, as tab drop will open a new tab normally if the same file is already not open. But it can be kept as a separate option as well. Also IMO, never bad to have multiple options :)
Do let me know your thoughts on this. If this looks good and needs any documenting, happy to work on that as well.
Thanks!

feat(esupports.hop): Add tab drop as option for open_mode

---

lua/neorg/modules/core/dirman/utils/module.lua
lua/neorg/modules/core/tangle/module.lua

as discussed on discord with `@bucdany`. This must have been missed when we switched to pathlib

fix: weird tangle file path logic

---

lua/neorg/core/config.lua

If you install neovim using [MSYS 2](https://www.msys2.org/), the operating system will be `mingw32_nt-<ver>`.
in my case it was `mingw32_nt-10.0`.
Therefore, it is necessary to add a check for the prefix `mingw32_nt` to see if the operating system is Windows

Add MINGW32_NT to get_os_info

---

lua/neorg/modules/core/dirman/module.lua

This is a pretty useful function

feat(dirman): in_workspace function

---

lua/neorg/modules/core/journal/module.lua

There's no reason these should be private, and someone asked for them to be public to use them in an external module they're working on

feat: make journal methods public

---

lua/neorg/modules/core/neorgcmd/module.lua

Allows `:Neorg` to take a range, and passes the data we get in the command callback along with the `content` field in the event.

feat: support ranges in neorgcmd

---

lua/neorg/modules/core/keybinds/module.lua

Add back the "gO" keybind for ToC, which was removed in https://github.com/nvim-neorg/neorg/commit/3dd946ae976ee45147a60eeb5174f0f951f04f94.

feat(keybinds): add back keybind "gO" for ToC

---

lua/neorg/modules/core/qol/toc/module.lua

fixes #1630 
issue introduced in #1221

fix(toc): only capture first detached modifier

---

lua/neorg/modules/core/export/module.lua

small export module refactor to allow for the `:'<,'>Neorg export to-clipboard markdown` command.
This copies the range to clipboard (or current line when no range is explicitly passed.

feat(export): copy to clipboard

---

lua/neorg/modules/core/dirman/module.lua

Ability to dynamically set the default workspace based on the `cwd`.
This gives you the ability to open different workspaces based on context for example:
```lua
config = {
workspaces = {
dev = '~/notes/dev',
personal = '~/notes/personal',
},
default_workspace = function()
local git_root = vim.fs.root(0, '.git')
local basename = vim.fs.basename(git_root)
if basename == 'dotfiles' then
return 'dev'
end
return 'personal'
end,
},
```

feat(dirman): dynamically set default workspace

---

lua/neorg/modules/core/tangle/module.lua

The current implementation keeps the fd open for each file it is tangling, which results in tangled shell scripts not being able to be run until the instance is closed

fix: Tangle should close fd for files

---

lua/neorg/modules/core/tangle/module.lua

Currently the lack of error handing causes a bad file descriptor error, which results in empty tangled files.
I also changed `vim.loop`, as its deprecated in favor of `vim.uv`

fix(tangle): proper error handling for fs_close

---

lua/neorg/core/modules.lua
lua/neorg/modules/core/qol/todo_items/module.lua

- Adds an event for when tasks todo status is changed
- Exposes a function which updates a task when given a buffer, line number and character
With this change, Neorg Query is able to update the "source task" when a user changes the status of a task in a query result.

feat(todo_items): todo-changed event

---

.github/workflows/gendoc.yml

#1654: Use luarocks' GitHub actions

---

docgen/docgen.lua

#1655 caused the docgen to run for the first time in a while, and it's using nightly, so I think that something in nightly changed, and it's totally broken everything
attempting to fix

fix(docgen): load buffers after opening them

---

doc/cheatsheet.norg

Hello,
This commit/PR simply fixes a typo (`sensistive` → `sensitive`) in the cheatsheet file I noticed.
Thanks in advance!

docs(cheatsheet): fix a minor typo

---

lua/neorg/modules/core/integrations/treesitter/module.lua

- Added use_makefile, which is how nvim-treesitter builds the norg parser by default and which correctly adds the required compiler flags
- Removed a macOS build kludge that is no longer needed (and seems not to work anymore)
- Removed branch specification which is ignored when setting revision.
Tested on an Apple silicon machine running macOS 14.7, and an Intel machine running macOS running macOS 13.7.
Fixes nvim-neorg/tree-sitter-norg#45

Fixed tree-sitter-norg parser builds on MacOS.

---

lua/neorg/modules/core/esupports/indent/module.lua
lua/neorg/modules/core/promo/module.lua

This fixes `=` messing with the indentation of verbatim blocks when no language is injected (either because a parser doesn't exist/isn't installed, or because no language was specified). Sometimes this is used for diagrams, which get messed up if all lines are aligned with the tag start. The current implementation doesn't handle code blocks with `norg` as language (which i can't see a good use case for) and thus those won't get auto indented either
https://github.com/user-attachments/assets/c6d021cb-865c-4c3f-8df6-254d74096418

fix(esupports.indent): keep indentation of verbatim blocks without an injected TS parser

---

lua/neorg/modules/core/integrations/treesitter/module.lua

Little late, but, fixing the breakage caused by this commit https://github.com/neovim/neovim/commit/a0b52e7cb3d211e30c21464c4a4f4acecd6418c9
There are other places where we call `vim.treesitter.get_parser` without explicitly loading the buffer, but it seems like in all of those cases the buffer is already loaded.
I'm sure we'll find more and just fix them as we go

fix: load buffer before parsing with TS

---

.github/workflows/checks.yml
.github/workflows/gendoc.yml
.github/workflows/integration_tests.yml
.github/workflows/luarocks.yml
.github/workflows/semver.yml
.github/workflows/sponsors.yml
.github/workflows/stylua.yml
.github/workflows/tests.yml
.github/workflows/version_in_code.yml
README.md
neorg-scm-1.rockspec

The original `nvim-treesitter` package has been removed from luarocks a year ago, however there is a `nvim-treesitter-legacy-api` package which exposes the legacy module system API from `nvim-treesitter` that neorg requires in order to work properly, e.g. being able to install the norg parsers and interacting with them.

fix(rockspec): add `nvim-treesitter-legacy-api` dependency

---

docgen/docgen.lua
lua/neorg/modules/core/completion/module.lua
lua/neorg/modules/core/esupports/hop/module.lua
lua/neorg/modules/core/export/markdown/module.lua
lua/neorg/modules/core/export/module.lua
lua/neorg/modules/core/integrations/treesitter/module.lua
lua/neorg/modules/core/looking-glass/module.lua

This doesn't break compatibility with the master branch
supersedes #1738 
closes #1715

fix: compatibility with nvim-treesitter main branch
